spring.neo4j.graph.uri=bolt://127.0.0.1:7687
spring.neo4j.graph.username=neo4j
spring.neo4j.graph.password=password
spring.neo4j.graph.driver=AnotherNeo4jDriver

spring.neo4j.analytics.uri=bolt://127.0.0.1:7687
spring.neo4j.analytics.username=neo4j
spring.neo4j.analytics.password=password
spring.neo4j.analytics.driver=AnotherNeo4jDriver
