# =========================
# Custom properties
# =========================
bufferCap=100KB
bufferSize=1000

# =========================
# File appender
# =========================
appender.file.type=File
appender.file.fileName=GS_PROJECT_NAME.log
appender.file.layout.type=TextLayout

# =========================
# Console appender
# =========================
appender.console.type=Console
appender.console.layout.type=TextLayout

# =========================
# Root logger
# =========================
rootLogger.type=Root
rootLogger.level=info
rootLogger.appenderRef.ref=console

# =========================
# Custom logger
# =========================
logger.myLogger.type=Logger
logger.myLogger.level=info
logger.myLogger.tags=_app_*,_biz_*
logger.myLogger.bufferSize=${bufferSize}
logger.myLogger.appenderRef[0].ref=file
