// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v3.21.12
// source: service.proto

package triple

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
}

func (x *PingReq) Reset()         { *x = PingReq{} }
func (x *PingReq) String() string { return protoimpl.X.MessageStringOf(x) }
func (*PingReq) ProtoMessage()    {}
func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	return mi.MessageOf(x)
}
func (x *PingReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
}

func (x *PingResp) Reset()         { *x = PingResp{} }
func (x *PingResp) String() string { return protoimpl.X.MessageStringOf(x) }
func (*PingResp) ProtoMessage()    {}
func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	return mi.MessageOf(x)
}
func (x *PingResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	UserId int64   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Amount float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount"`
	Status int32   `protobuf:"varint,4,opt,name=status,proto3" json:"status"`
}

func (x *Order) Reset()         { *x = Order{} }
func (x *Order) String() string { return protoimpl.X.MessageStringOf(x) }
func (*Order) ProtoMessage()    {}
func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	return mi.MessageOf(x)
}
func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}
func (x *Order) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}
func (x *Order) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}
func (x *Order) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	UserId int64   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Amount float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount"`
}

func (x *CreateOrderReq) Reset()         { *x = CreateOrderReq{} }
func (x *CreateOrderReq) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CreateOrderReq) ProtoMessage()    {}
func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	return mi.MessageOf(x)
}
func (x *CreateOrderReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}
func (x *CreateOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}
func (x *CreateOrderReq) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type OrderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Data    *Order `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *OrderResp) Reset()         { *x = OrderResp{} }
func (x *OrderResp) String() string { return protoimpl.X.MessageStringOf(x) }
func (*OrderResp) ProtoMessage()    {}
func (x *OrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	return mi.MessageOf(x)
}
func (x *OrderResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}
func (x *OrderResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}
func (x *OrderResp) GetData() *Order {
	if x != nil {
		return x.Data
	}
	return nil
}

type PayOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
}

func (x *PayOrderReq) Reset()         { *x = PayOrderReq{} }
func (x *PayOrderReq) String() string { return protoimpl.X.MessageStringOf(x) }
func (*PayOrderReq) ProtoMessage()    {}
func (x *PayOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	return mi.MessageOf(x)
}
func (x *PayOrderReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ShipOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
}

func (x *ShipOrderReq) Reset()         { *x = ShipOrderReq{} }
func (x *ShipOrderReq) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ShipOrderReq) ProtoMessage()    {}
func (x *ShipOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	return mi.MessageOf(x)
}
func (x *ShipOrderReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email"`
	Level int32  `protobuf:"varint,4,opt,name=level,proto3" json:"level"`
}

func (x *User) Reset()         { *x = User{} }
func (x *User) String() string { return protoimpl.X.MessageStringOf(x) }
func (*User) ProtoMessage()    {}
func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	return mi.MessageOf(x)
}
func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}
func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}
func (x *User) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type RegisterUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email"`
}

func (x *RegisterUserReq) Reset()         { *x = RegisterUserReq{} }
func (x *RegisterUserReq) String() string { return protoimpl.X.MessageStringOf(x) }
func (*RegisterUserReq) ProtoMessage()    {}
func (x *RegisterUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	return mi.MessageOf(x)
}
func (x *RegisterUserReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}
func (x *RegisterUserReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *RegisterUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Data    *User  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UserResp) Reset()         { *x = UserResp{} }
func (x *UserResp) String() string { return protoimpl.X.MessageStringOf(x) }
func (*UserResp) ProtoMessage()    {}
func (x *UserResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	return mi.MessageOf(x)
}
func (x *UserResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}
func (x *UserResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}
func (x *UserResp) GetData() *User {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpgradeUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
}

func (x *UpgradeUserReq) Reset()         { *x = UpgradeUserReq{} }
func (x *UpgradeUserReq) String() string { return protoimpl.X.MessageStringOf(x) }
func (*UpgradeUserReq) ProtoMessage()    {}
func (x *UpgradeUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	return mi.MessageOf(x)
}
func (x *UpgradeUserReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// The FileDescriptor raw bytes are elided from this hand-written template.
// A real `protoc --go_out=...` run would embed the serialized descriptor here.
var File_service_proto protoreflect.FileDescriptor

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_service_proto_goTypes = []interface{}{
	(*PingReq)(nil),         // 0: gs_project_name.PingReq
	(*PingResp)(nil),        // 1: gs_project_name.PingResp
	(*Order)(nil),           // 2: gs_project_name.Order
	(*CreateOrderReq)(nil),  // 3: gs_project_name.CreateOrderReq
	(*OrderResp)(nil),       // 4: gs_project_name.OrderResp
	(*PayOrderReq)(nil),     // 5: gs_project_name.PayOrderReq
	(*ShipOrderReq)(nil),    // 6: gs_project_name.ShipOrderReq
	(*User)(nil),            // 7: gs_project_name.User
	(*RegisterUserReq)(nil), // 8: gs_project_name.RegisterUserReq
	(*UserResp)(nil),        // 9: gs_project_name.UserResp
	(*UpgradeUserReq)(nil),  // 10: gs_project_name.UpgradeUserReq
}

var (
	file_service_proto_rawDescOnce sync.Once
	_                              = reflect.TypeOf
)
