spring.gorm.clickhouse.primary.user=default
spring.gorm.clickhouse.primary.password=
spring.gorm.clickhouse.primary.addr=127.0.0.1:9000
spring.gorm.clickhouse.primary.db=default

spring.gorm.clickhouse.replica.user=default
spring.gorm.clickhouse.replica.password=
spring.gorm.clickhouse.replica.addr=127.0.0.1:9000
spring.gorm.clickhouse.replica.db=default
