# Disable the built-in HTTP server.
spring.http.server.enabled=false

spring.grpc.server.addr=:9494
spring.grpc.server.health.enabled=true
spring.grpc.server.maxRecvMsgSize=4194304
spring.grpc.server.maxSendMsgSize=4194304

spring.grpc.server.interceptor.tracing.enabled=true
spring.grpc.server.interceptor.metrics.enabled=true

spring.observability.enable=true
spring.observability.service-name=grpc-otel-example
spring.observability.trace.exporter=otlp-grpc
spring.observability.trace.endpoint=127.0.0.1:4317
spring.observability.trace.insecure=true
spring.observability.trace.sampler-ratio=1.0

spring.observability.metrics.exporter=prometheus
spring.observability.metrics.port=9090
spring.observability.metrics.path=/metrics