// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: payload.proto

// NOTE: the file descriptor byte blobs a real protoc-gen-go run emits are
// elided; only the Frame struct + accessors that the goframe TCP server needs
// are kept. Regenerating from payload.proto restores the descriptor tables.

package pb

import (
	"fmt"
)

// Frame is the length-prefixed payload exchanged on the raw TCP socket.
type Frame struct {
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Body []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Seq  int64  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *Frame) Reset()         { *x = Frame{} }
func (x *Frame) String() string { return fmt.Sprintf("%+v", *x) }
func (*Frame) ProtoMessage()    {}

func (x *Frame) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Frame) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Frame) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}
