// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

// PingReq is the request payload for the /ping health-check endpoint.
type PingReq struct {
	Name string `form:"name,optional"`
}

// PingResp is the response payload returned by /ping.
type PingResp struct {
	Message string `json:"message"`
}

// Order is the go-zero view of an order aggregate exposed over HTTP.
type Order struct {
	Id     string  `json:"id"`
	UserId string  `json:"user_id"`
	Amount float64 `json:"amount"`
	Status int32   `json:"status"`
}

// CreateOrderReq is the request payload for creating an order.
type CreateOrderReq struct {
	Id     string  `json:"id"`
	UserId string  `json:"user_id"`
	Amount float64 `json:"amount"`
}

// OrderResp is the envelope response for order-related endpoints.
type OrderResp struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
	Data    *Order `json:"data,omitempty"`
}

// PayOrderReq is the request payload for paying an order.
type PayOrderReq struct {
	Id string `path:"id"`
}

// ShipOrderReq is the request payload for shipping an order.
type ShipOrderReq struct {
	Id string `path:"id"`
}

// User is the go-zero view of a user aggregate exposed over HTTP.
type User struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
	Level int32  `json:"level"`
}

// RegisterUserReq is the request payload for registering a new user.
type RegisterUserReq struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

// UserResp is the envelope response for user-related endpoints.
type UserResp struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
	Data    *User  `json:"data,omitempty"`
}

// UpgradeUserReq is the request payload for upgrading a user's level.
type UpgradeUserReq struct {
	Id string `path:"id"`
}
