spring.redigo.addr=127.0.0.1:6379
spring.redigo.driver=AnotherRedisDriver

spring.redigo.instances.a.addr=127.0.0.1:6379
spring.redigo.instances.a.driver=AnotherRedisDriver

spring.redigo.instances.b.addr=127.0.0.1:6379
spring.redigo.instances.b.driver=AnotherRedisDriver