// Code generated by Kitex v0.16.3. DO NOT EDIT.

package echo

import (
	"context"

	"github.com/cloudwego/prutal"
)

type EchoRequest struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (x *EchoRequest) Reset() { *x = EchoRequest{} }

func (x *EchoRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *EchoRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (x *EchoResponse) Reset() { *x = EchoResponse{} }

func (x *EchoResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *EchoResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *EchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoService interface {
	Echo(ctx context.Context, req *EchoRequest) (res *EchoResponse, err error)
}
