spring.rocketmq.instances.a.name-servers=127.0.0.1:9876
spring.rocketmq.instances.a.fail-fast=true
spring.rocketmq.instances.a.send-timeout=5s

spring.observability.enable=true
spring.observability.service-name=rocketmq-otel-example
spring.observability.trace.exporter=otlp-grpc
spring.observability.trace.endpoint=127.0.0.1:4317
spring.observability.trace.insecure=true
spring.observability.trace.sampler-ratio=1.0
spring.observability.metrics.exporter=prometheus
spring.observability.metrics.port=9090
spring.observability.metrics.path=/metrics
