spring.gorm.mysql.primary.user=root
spring.gorm.mysql.primary.password=123456
spring.gorm.mysql.primary.addr=127.0.0.1:3306
spring.gorm.mysql.primary.db=test

spring.gorm.mysql.replica.user=root
spring.gorm.mysql.replica.password=123456
spring.gorm.mysql.replica.addr=127.0.0.1:3306
spring.gorm.mysql.replica.db=test
