spring.gorm.primary.user=root
spring.gorm.primary.password=123456
spring.gorm.primary.addr=127.0.0.1:3306
spring.gorm.primary.db=test

spring.gorm.replica.user=root
spring.gorm.replica.password=123456
spring.gorm.replica.addr=127.0.0.1:3306
spring.gorm.replica.db=test
