// Code generated by gs-http-gen compiler. DO NOT EDIT.

package proto

import (
	"errors"
	"fmt"
	"net/http"
	"strings"
)

var _ = errors.New
var _ = strings.Count
var _ = http.NewServeMux

const MIN_AMOUNT float64 = 0.01

const MAX_AMOUNT float64 = 1000000.0

// Order status
type OrderStatus int32

const (
	OrderStatus_Pending OrderStatus = 0
	OrderStatus_Paid    OrderStatus = 1
	OrderStatus_Shipped OrderStatus = 2
)

var (
	OrderStatus_name = map[OrderStatus]string{
		0: "Pending",
		1: "Paid",
		2: "Shipped",
	}
	OrderStatus_value = map[string]OrderStatus{
		"Pending": 0,
		"Paid":    1,
		"Shipped": 2,
	}
)

// OrderStatusAsString wraps OrderStatus to encode/decode as a JSON string
type OrderStatusAsString OrderStatus

// MarshalJSON implements custom JSON encoding for the enum as a string
func (x OrderStatusAsString) MarshalJSON() ([]byte, error) {
	if s, ok := OrderStatus_name[OrderStatus(x)]; ok {
		return []byte(fmt.Sprintf("\"%s\"", s)), nil
	}
	return nil, fmt.Errorf("invalid OrderStatus: %d", x)
}

// UnmarshalJSON implements custom JSON decoding for the enum from a string
func (x *OrderStatusAsString) UnmarshalJSON(data []byte) error {
	str := strings.Trim(string(data), "\"")
	if v, ok := OrderStatus_value[str]; ok {
		*x = OrderStatusAsString(v)
		return nil
	}
	return fmt.Errorf("invalid OrderStatus value: %q", str)
}

// OneOfOrderStatus is usually used for validation.
func OneOfOrderStatus(i OrderStatus) bool {
	_, ok := OrderStatus_name[i]
	return ok
}

type Order struct {
	Id     string      `json:"Id"`
	UserId string      `json:"UserId"`
	Amount float64     `json:"Amount"`
	Status OrderStatus `json:"Status"`
}

// NewOrder creates a new instance of the struct and sets default values if defined
func NewOrder() *Order {
	return &Order{}
}

// New implements the Object interface
func (x *Order) New() any {
	return NewOrder()
}

// GetId returns the value of Id
func (x *Order) GetId() (r string) {
	if x != nil {
		return x.Id
	}
	return r
}

// SetId sets the value of Id
func (x *Order) SetId(v string) {
	if x != nil {
		x.Id = v
	}
}

// GetUserId returns the value of UserId
func (x *Order) GetUserId() (r string) {
	if x != nil {
		return x.UserId
	}
	return r
}

// SetUserId sets the value of UserId
func (x *Order) SetUserId(v string) {
	if x != nil {
		x.UserId = v
	}
}

// GetAmount returns the value of Amount
func (x *Order) GetAmount() (r float64) {
	if x != nil {
		return x.Amount
	}
	return r
}

// SetAmount sets the value of Amount
func (x *Order) SetAmount(v float64) {
	if x != nil {
		x.Amount = v
	}
}

// GetStatus returns the value of Status
func (x *Order) GetStatus() (r OrderStatus) {
	if x != nil {
		return x.Status
	}
	return r
}

// SetStatus sets the value of Status
func (x *Order) SetStatus(v OrderStatus) {
	if x != nil {
		x.Status = v
	}
}

// Binding extracts non-body values (header, path, query) from *http.Request
func (x *Order) Binding(r *http.Request) error {
	return nil
}

// Validate checks field values using generated validation expressions
func (x *Order) Validate() error {
	if !(len(x.Id) > 0 && len(x.Id) <= 64) {
		return errors.New("validate failed on Order.Id")
	}
	if !(len(x.UserId) > 0 && len(x.UserId) <= 64) {
		return errors.New("validate failed on Order.UserId")
	}
	if !(x.Amount >= MIN_AMOUNT && x.Amount <= MAX_AMOUNT) {
		return errors.New("validate failed on Order.Amount")
	}
	return nil
}

func (x *Order) String() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Order(%+v)", *x)
}

type CreateOrderReq struct {
	Id     string  `json:"Id"`
	UserId string  `json:"UserId"`
	Amount float64 `json:"Amount"`
}

// NewCreateOrderReq creates a new instance of the struct and sets default values if defined
func NewCreateOrderReq() *CreateOrderReq {
	return &CreateOrderReq{}
}

// New implements the Object interface
func (x *CreateOrderReq) New() any {
	return NewCreateOrderReq()
}

// GetId returns the value of Id
func (x *CreateOrderReq) GetId() (r string) {
	if x != nil {
		return x.Id
	}
	return r
}

// SetId sets the value of Id
func (x *CreateOrderReq) SetId(v string) {
	if x != nil {
		x.Id = v
	}
}

// GetUserId returns the value of UserId
func (x *CreateOrderReq) GetUserId() (r string) {
	if x != nil {
		return x.UserId
	}
	return r
}

// SetUserId sets the value of UserId
func (x *CreateOrderReq) SetUserId(v string) {
	if x != nil {
		x.UserId = v
	}
}

// GetAmount returns the value of Amount
func (x *CreateOrderReq) GetAmount() (r float64) {
	if x != nil {
		return x.Amount
	}
	return r
}

// SetAmount sets the value of Amount
func (x *CreateOrderReq) SetAmount(v float64) {
	if x != nil {
		x.Amount = v
	}
}

// Binding extracts non-body values (header, path, query) from *http.Request
func (x *CreateOrderReq) Binding(r *http.Request) error {
	return nil
}

// Validate checks field values using generated validation expressions
func (x *CreateOrderReq) Validate() error {
	if !(len(x.Id) > 0 && len(x.Id) <= 64) {
		return errors.New("validate failed on CreateOrderReq.Id")
	}
	if !(len(x.UserId) > 0 && len(x.UserId) <= 64) {
		return errors.New("validate failed on CreateOrderReq.UserId")
	}
	if !(x.Amount >= MIN_AMOUNT && x.Amount <= MAX_AMOUNT) {
		return errors.New("validate failed on CreateOrderReq.Amount")
	}
	return nil
}

func (x *CreateOrderReq) String() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderReq(%+v)", *x)
}

type CreateOrderResp struct {
	Errno  ErrCode `json:"Errno"`
	Errmsg string  `json:"Errmsg"`
	Data   *Order  `json:"Data,omitempty"`
}

// NewCreateOrderResp creates a new instance of the struct and sets default values if defined
func NewCreateOrderResp() *CreateOrderResp {
	return &CreateOrderResp{}
}

// New implements the Object interface
func (x *CreateOrderResp) New() any {
	return NewCreateOrderResp()
}

// GetErrno returns the value of Errno
func (x *CreateOrderResp) GetErrno() (r ErrCode) {
	if x != nil {
		return x.Errno
	}
	return r
}

// SetErrno sets the value of Errno
func (x *CreateOrderResp) SetErrno(v ErrCode) {
	if x != nil {
		x.Errno = v
	}
}

// GetErrmsg returns the value of Errmsg
func (x *CreateOrderResp) GetErrmsg() (r string) {
	if x != nil {
		return x.Errmsg
	}
	return r
}

// SetErrmsg sets the value of Errmsg
func (x *CreateOrderResp) SetErrmsg(v string) {
	if x != nil {
		x.Errmsg = v
	}
}

// GetData returns the value of Data
func (x *CreateOrderResp) GetData() (r *Order) {
	if x != nil {
		return x.Data
	}
	return r
}

// SetData sets the value of Data
func (x *CreateOrderResp) SetData(v *Order) {
	if x != nil {
		x.Data = v
	}
}

// Binding extracts non-body values (header, path, query) from *http.Request
func (x *CreateOrderResp) Binding(r *http.Request) error {
	return nil
}

// Validate checks field values using generated validation expressions
func (x *CreateOrderResp) Validate() error {
	return nil
}

func (x *CreateOrderResp) String() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderResp(%+v)", *x)
}

type PayOrderReq struct {
	Id string `json:"Id" path:"id"`
}

// NewPayOrderReq creates a new instance of the struct and sets default values if defined
func NewPayOrderReq() *PayOrderReq {
	return &PayOrderReq{}
}

// New implements the Object interface
func (x *PayOrderReq) New() any {
	return NewPayOrderReq()
}

// GetId returns the value of Id
func (x *PayOrderReq) GetId() (r string) {
	if x != nil {
		return x.Id
	}
	return r
}

// SetId sets the value of Id
func (x *PayOrderReq) SetId(v string) {
	if x != nil {
		x.Id = v
	}
}

// Binding extracts non-body values (header, path, query) from *http.Request
func (x *PayOrderReq) Binding(r *http.Request) error {
	return Binding(r, []BindingField{
		{"PayOrderReq.Id", "path", "id", &x.Id},
	})
}

// Validate checks field values using generated validation expressions
func (x *PayOrderReq) Validate() error {
	if !(len(x.Id) > 0 && len(x.Id) <= 64) {
		return errors.New("validate failed on PayOrderReq.Id")
	}
	return nil
}

func (x *PayOrderReq) String() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PayOrderReq(%+v)", *x)
}

type PayOrderResp struct {
	Errno  ErrCode `json:"Errno"`
	Errmsg string  `json:"Errmsg"`
	Data   *Order  `json:"Data,omitempty"`
}

// NewPayOrderResp creates a new instance of the struct and sets default values if defined
func NewPayOrderResp() *PayOrderResp {
	return &PayOrderResp{}
}

// New implements the Object interface
func (x *PayOrderResp) New() any {
	return NewPayOrderResp()
}

// GetErrno returns the value of Errno
func (x *PayOrderResp) GetErrno() (r ErrCode) {
	if x != nil {
		return x.Errno
	}
	return r
}

// SetErrno sets the value of Errno
func (x *PayOrderResp) SetErrno(v ErrCode) {
	if x != nil {
		x.Errno = v
	}
}

// GetErrmsg returns the value of Errmsg
func (x *PayOrderResp) GetErrmsg() (r string) {
	if x != nil {
		return x.Errmsg
	}
	return r
}

// SetErrmsg sets the value of Errmsg
func (x *PayOrderResp) SetErrmsg(v string) {
	if x != nil {
		x.Errmsg = v
	}
}

// GetData returns the value of Data
func (x *PayOrderResp) GetData() (r *Order) {
	if x != nil {
		return x.Data
	}
	return r
}

// SetData sets the value of Data
func (x *PayOrderResp) SetData(v *Order) {
	if x != nil {
		x.Data = v
	}
}

// Binding extracts non-body values (header, path, query) from *http.Request
func (x *PayOrderResp) Binding(r *http.Request) error {
	return nil
}

// Validate checks field values using generated validation expressions
func (x *PayOrderResp) Validate() error {
	return nil
}

func (x *PayOrderResp) String() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PayOrderResp(%+v)", *x)
}

type ShipOrderReq struct {
	Id string `json:"Id" path:"id"`
}

// NewShipOrderReq creates a new instance of the struct and sets default values if defined
func NewShipOrderReq() *ShipOrderReq {
	return &ShipOrderReq{}
}

// New implements the Object interface
func (x *ShipOrderReq) New() any {
	return NewShipOrderReq()
}

// GetId returns the value of Id
func (x *ShipOrderReq) GetId() (r string) {
	if x != nil {
		return x.Id
	}
	return r
}

// SetId sets the value of Id
func (x *ShipOrderReq) SetId(v string) {
	if x != nil {
		x.Id = v
	}
}

// Binding extracts non-body values (header, path, query) from *http.Request
func (x *ShipOrderReq) Binding(r *http.Request) error {
	return Binding(r, []BindingField{
		{"ShipOrderReq.Id", "path", "id", &x.Id},
	})
}

// Validate checks field values using generated validation expressions
func (x *ShipOrderReq) Validate() error {
	if !(len(x.Id) > 0 && len(x.Id) <= 64) {
		return errors.New("validate failed on ShipOrderReq.Id")
	}
	return nil
}

func (x *ShipOrderReq) String() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ShipOrderReq(%+v)", *x)
}

type ShipOrderResp struct {
	Errno  ErrCode `json:"Errno"`
	Errmsg string  `json:"Errmsg"`
	Data   *Order  `json:"Data,omitempty"`
}

// NewShipOrderResp creates a new instance of the struct and sets default values if defined
func NewShipOrderResp() *ShipOrderResp {
	return &ShipOrderResp{}
}

// New implements the Object interface
func (x *ShipOrderResp) New() any {
	return NewShipOrderResp()
}

// GetErrno returns the value of Errno
func (x *ShipOrderResp) GetErrno() (r ErrCode) {
	if x != nil {
		return x.Errno
	}
	return r
}

// SetErrno sets the value of Errno
func (x *ShipOrderResp) SetErrno(v ErrCode) {
	if x != nil {
		x.Errno = v
	}
}

// GetErrmsg returns the value of Errmsg
func (x *ShipOrderResp) GetErrmsg() (r string) {
	if x != nil {
		return x.Errmsg
	}
	return r
}

// SetErrmsg sets the value of Errmsg
func (x *ShipOrderResp) SetErrmsg(v string) {
	if x != nil {
		x.Errmsg = v
	}
}

// GetData returns the value of Data
func (x *ShipOrderResp) GetData() (r *Order) {
	if x != nil {
		return x.Data
	}
	return r
}

// SetData sets the value of Data
func (x *ShipOrderResp) SetData(v *Order) {
	if x != nil {
		x.Data = v
	}
}

// Binding extracts non-body values (header, path, query) from *http.Request
func (x *ShipOrderResp) Binding(r *http.Request) error {
	return nil
}

// Validate checks field values using generated validation expressions
func (x *ShipOrderResp) Validate() error {
	return nil
}

func (x *ShipOrderResp) String() string {
	if x == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ShipOrderResp(%+v)", *x)
}
