// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: greet.proto

package greet

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// GreetServiceService defines service.
type GreetServiceService interface {
	Greet(ctx context.Context, req *GreetRequest) (*GreetResponse, error)
}

func GreetServiceService_Greet_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GreetRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(GreetServiceService).Greet(ctx, reqbody.(*GreetRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// GreetServiceServer_ServiceDesc descriptor for server.RegisterService.
var GreetServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.helloworld.greet.GreetService",
	HandlerType: ((*GreetServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.helloworld.greet.GreetService/Greet",
			Func: GreetServiceService_Greet_Handler,
		},
	},
}

// RegisterGreetServiceService registers service.
func RegisterGreetServiceService(s server.Service, svr GreetServiceService) {
	if err := s.Register(&GreetServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("GreetService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedGreetService struct{}

func (s *UnimplementedGreetService) Greet(ctx context.Context, req *GreetRequest) (*GreetResponse, error) {
	return nil, errors.New("rpc Greet of service GreetService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// GreetServiceClientProxy defines service client proxy
type GreetServiceClientProxy interface {
	Greet(ctx context.Context, req *GreetRequest, opts ...client.Option) (rsp *GreetResponse, err error)
}

type GreetServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewGreetServiceClientProxy = func(opts ...client.Option) GreetServiceClientProxy {
	return &GreetServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *GreetServiceClientProxyImpl) Greet(ctx context.Context, req *GreetRequest, opts ...client.Option) (*GreetResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.helloworld.greet.GreetService/Greet")
	msg.WithCalleeServiceName(GreetServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("helloworld")
	msg.WithCalleeServer("greet")
	msg.WithCalleeService("GreetService")
	msg.WithCalleeMethod("Greet")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GreetResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
