# Define a go-redis client instance
spring.go-redis.instances.main.addr=127.0.0.1:6379

# Define a redigo client instance
spring.redigo.instances.main.addr=127.0.0.1:6379

# Define a MySQL instance with GORM
spring.gorm.instances.main.user=root
spring.gorm.instances.main.password=123456
spring.gorm.instances.main.addr=127.0.0.1:3306
spring.gorm.instances.main.db=test

# Custom logger settings
logging.logger.myLogger.type=RollingFileLogger
logging.logger.myLogger.level=info
logging.logger.myLogger.tag=_app_*,_biz_*
logging.logger.myLogger.dir=./logs
logging.logger.myLogger.file=GS_PROJECT_NAME.log
logging.logger.myLogger.layout.type=TextLayout
logging.logger.myLogger.async=true
logging.logger.myLogger.bufferSize=1000

# HTTP server
spring.web.server.port=8080

recovery.msg=recovery
trace.msg=trace
metric.msg=metric
