spring.go-redis.addr=127.0.0.1:6379
spring.go-redis.driver=AnotherRedisDriver

spring.go-redis.instances.a.addr=127.0.0.1:6379
spring.go-redis.instances.a.driver=AnotherRedisDriver

spring.go-redis.instances.b.addr=127.0.0.1:6379
spring.go-redis.instances.b.driver=AnotherRedisDriver