// Code generated by gs-mock v0.0.8. DO NOT EDIT.
// Tool: https://github.com/go-spring/gs-mock
// gs mock -o gs_mock.go -i 'ConditionContext,ArgContext'

package gs

import (
	"reflect"

	"github.com/go-spring/gs-mock/gsmock"
)

// ConditionContextMockImpl is a generated mock implementation of the ConditionContext interface.
type ConditionContextMockImpl struct {
	r *gsmock.Manager
}

// NewConditionContextMockImpl creates a new mock instance for ConditionContext with the given
// gsmock.Manager. Returns an initialized struct ready for registering mock behavior.
func NewConditionContextMockImpl(r *gsmock.Manager) *ConditionContextMockImpl {
	return &ConditionContextMockImpl{r: r}
}

//go:noinline
func (impl *ConditionContextMockImpl) funcHas() func(key string) bool {
	return impl.Has
}

// Has calls the registered mock for Has via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *ConditionContextMockImpl) Has(key string) bool {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcHas(), key); ok {
		return gsmock.Unbox1[bool](ret)
	}
	panic("no mock code matched for ConditionContextMockImpl.Has")
}

// MockHas returns a Mocker11
// for registering mock behavior of Has with specific parameter and return types.
func (impl *ConditionContextMockImpl) MockHas() *gsmock.Mocker11[string, bool] {
	return gsmock.Method11(impl, impl.funcHas(), impl.r)
}

//go:noinline
func (impl *ConditionContextMockImpl) funcProp() func(key string) (string, bool) {
	return impl.Prop
}

// Prop calls the registered mock for Prop via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *ConditionContextMockImpl) Prop(key string) (string, bool) {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcProp(), key); ok {
		return gsmock.Unbox2[string, bool](ret)
	}
	panic("no mock code matched for ConditionContextMockImpl.Prop")
}

// MockProp returns a Mocker12
// for registering mock behavior of Prop with specific parameter and return types.
func (impl *ConditionContextMockImpl) MockProp() *gsmock.Mocker12[string, string, bool] {
	return gsmock.Method12(impl, impl.funcProp(), impl.r)
}

//go:noinline
func (impl *ConditionContextMockImpl) funcFind() func(beanID BeanID) ([]ConditionBean, error) {
	return impl.Find
}

// Find calls the registered mock for Find via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *ConditionContextMockImpl) Find(beanID BeanID) ([]ConditionBean, error) {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcFind(), beanID); ok {
		return gsmock.Unbox2[[]ConditionBean, error](ret)
	}
	panic("no mock code matched for ConditionContextMockImpl.Find")
}

// MockFind returns a Mocker12
// for registering mock behavior of Find with specific parameter and return types.
func (impl *ConditionContextMockImpl) MockFind() *gsmock.Mocker12[BeanID, []ConditionBean, error] {
	return gsmock.Method12(impl, impl.funcFind(), impl.r)
}

// ArgContextMockImpl is a generated mock implementation of the ArgContext interface.
type ArgContextMockImpl struct {
	r *gsmock.Manager
}

// NewArgContextMockImpl creates a new mock instance for ArgContext with the given
// gsmock.Manager. Returns an initialized struct ready for registering mock behavior.
func NewArgContextMockImpl(r *gsmock.Manager) *ArgContextMockImpl {
	return &ArgContextMockImpl{r: r}
}

//go:noinline
func (impl *ArgContextMockImpl) funcCheck() func(c Condition) (bool, error) {
	return impl.Check
}

// Check calls the registered mock for Check via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *ArgContextMockImpl) Check(c Condition) (bool, error) {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcCheck(), c); ok {
		return gsmock.Unbox2[bool, error](ret)
	}
	panic("no mock code matched for ArgContextMockImpl.Check")
}

// MockCheck returns a Mocker12
// for registering mock behavior of Check with specific parameter and return types.
func (impl *ArgContextMockImpl) MockCheck() *gsmock.Mocker12[Condition, bool, error] {
	return gsmock.Method12(impl, impl.funcCheck(), impl.r)
}

//go:noinline
func (impl *ArgContextMockImpl) funcBind() func(v reflect.Value, tag string) error {
	return impl.Bind
}

// Bind calls the registered mock for Bind via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *ArgContextMockImpl) Bind(v reflect.Value, tag string) error {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcBind(), v, tag); ok {
		return gsmock.Unbox1[error](ret)
	}
	panic("no mock code matched for ArgContextMockImpl.Bind")
}

// MockBind returns a Mocker21
// for registering mock behavior of Bind with specific parameter and return types.
func (impl *ArgContextMockImpl) MockBind() *gsmock.Mocker21[reflect.Value, string, error] {
	return gsmock.Method21(impl, impl.funcBind(), impl.r)
}

//go:noinline
func (impl *ArgContextMockImpl) funcWire() func(v reflect.Value, tag string) error {
	return impl.Wire
}

// Wire calls the registered mock for Wire via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *ArgContextMockImpl) Wire(v reflect.Value, tag string) error {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcWire(), v, tag); ok {
		return gsmock.Unbox1[error](ret)
	}
	panic("no mock code matched for ArgContextMockImpl.Wire")
}

// MockWire returns a Mocker21
// for registering mock behavior of Wire with specific parameter and return types.
func (impl *ArgContextMockImpl) MockWire() *gsmock.Mocker21[reflect.Value, string, error] {
	return gsmock.Method21(impl, impl.funcWire(), impl.r)
}
