apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Production overlay: more replicas and tighter resource requests/limits.
namespace: GS_APP_NAME-prod

resources:
  - ../../base

replicas:
  - name: GS_APP_NAME
    count: 3

images:
  - name: GS_IMAGE
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: GS_APP_NAME
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 250m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
