// Code generated by protoc-gen-triple. DO NOT EDIT.
//
// Source: service.proto
package triple

import (
	"context"
)

// The real generated file imports:
//
//	"dubbo.apache.org/dubbo-go/v3"
//	"dubbo.apache.org/dubbo-go/v3/client"
//	"dubbo.apache.org/dubbo-go/v3/common"
//	"dubbo.apache.org/dubbo-go/v3/common/constant"
//	"dubbo.apache.org/dubbo-go/v3/protocol/triple/triple_protocol"
//	"dubbo.apache.org/dubbo-go/v3/server"
//
// The scaffold keeps the interface + constants believable but drops the
// dubbo-go dependency so `idl/dubbo/triple` stays a leaf package
// callers can compile without pulling in the runtime. When the project
// wires a real dubbo server, replace this file with the true generator
// output and swap the `any` in RegisterGS_PROJECT_NAMEServiceHandler for
// *server.Server.

const (
	// GS_PROJECT_NAMEServiceName is the fully-qualified name of the GS_PROJECT_NAMEService service.
	GS_PROJECT_NAMEServiceName = "gs_project_name.GS_PROJECT_NAMEService"
)

// These constants are the fully-qualified names of the RPCs defined in this
// package. They are exposed at runtime as procedure paths and as the final
// two segments of the HTTP route.
const (
	GS_PROJECT_NAMEServicePingProcedure         = "/gs_project_name.GS_PROJECT_NAMEService/Ping"
	GS_PROJECT_NAMEServiceCreateOrderProcedure  = "/gs_project_name.GS_PROJECT_NAMEService/CreateOrder"
	GS_PROJECT_NAMEServicePayOrderProcedure     = "/gs_project_name.GS_PROJECT_NAMEService/PayOrder"
	GS_PROJECT_NAMEServiceShipOrderProcedure    = "/gs_project_name.GS_PROJECT_NAMEService/ShipOrder"
	GS_PROJECT_NAMEServiceRegisterUserProcedure = "/gs_project_name.GS_PROJECT_NAMEService/RegisterUser"
	GS_PROJECT_NAMEServiceUpgradeUserProcedure  = "/gs_project_name.GS_PROJECT_NAMEService/UpgradeUser"
)

// GS_PROJECT_NAMEServiceHandler is an implementation of the
// gs_project_name.GS_PROJECT_NAMEService service.
type GS_PROJECT_NAMEServiceHandler interface {
	Ping(context.Context, *PingReq) (*PingResp, error)
	CreateOrder(context.Context, *CreateOrderReq) (*OrderResp, error)
	PayOrder(context.Context, *PayOrderReq) (*OrderResp, error)
	ShipOrder(context.Context, *ShipOrderReq) (*OrderResp, error)
	RegisterUser(context.Context, *RegisterUserReq) (*UserResp, error)
	UpgradeUser(context.Context, *UpgradeUserReq) (*UserResp, error)
}

// MethodInfo mirrors dubbo-go's server.MethodInfo shape at the call sites the
// scaffold needs, without depending on the real package. The real generator
// output replaces this alias with server.MethodInfo.
type MethodInfo struct {
	Name        string
	ReqInitFunc func() interface{}
	MethodFunc  func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error)
}

// ServiceInfo mirrors dubbo-go's server.ServiceInfo shape. See the comment on
// MethodInfo above.
type ServiceInfo struct {
	InterfaceName string
	ServiceType   interface{}
	Methods       []MethodInfo
}

// RegisterGS_PROJECT_NAMEServiceHandler registers hdlr on srv. In the real
// generated code srv is *server.Server; here it is `any` so the triple
// package stays dependency-free until the project wires a real dubbo server.
func RegisterGS_PROJECT_NAMEServiceHandler(srv any, hdlr GS_PROJECT_NAMEServiceHandler, opts ...any) error {
	// TODO: cast srv to *server.Server and call
	//   srv.Register(hdlr, &GS_PROJECT_NAMEService_ServiceInfo, opts...)
	_ = srv
	_ = hdlr
	_ = opts
	return nil
}

// GS_PROJECT_NAMEService_ServiceInfo describes the service to the dubbo
// runtime. The MethodFunc bodies unwrap the incoming args slice and hand off
// to the handler; the outer registration code wraps the return in a triple
// response.
var GS_PROJECT_NAMEService_ServiceInfo = ServiceInfo{
	InterfaceName: GS_PROJECT_NAMEServiceName,
	ServiceType:   (*GS_PROJECT_NAMEServiceHandler)(nil),
	Methods: []MethodInfo{
		{
			Name:        "Ping",
			ReqInitFunc: func() interface{} { return new(PingReq) },
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				return handler.(GS_PROJECT_NAMEServiceHandler).Ping(ctx, args[0].(*PingReq))
			},
		},
		{
			Name:        "CreateOrder",
			ReqInitFunc: func() interface{} { return new(CreateOrderReq) },
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				return handler.(GS_PROJECT_NAMEServiceHandler).CreateOrder(ctx, args[0].(*CreateOrderReq))
			},
		},
		{
			Name:        "PayOrder",
			ReqInitFunc: func() interface{} { return new(PayOrderReq) },
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				return handler.(GS_PROJECT_NAMEServiceHandler).PayOrder(ctx, args[0].(*PayOrderReq))
			},
		},
		{
			Name:        "ShipOrder",
			ReqInitFunc: func() interface{} { return new(ShipOrderReq) },
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				return handler.(GS_PROJECT_NAMEServiceHandler).ShipOrder(ctx, args[0].(*ShipOrderReq))
			},
		},
		{
			Name:        "RegisterUser",
			ReqInitFunc: func() interface{} { return new(RegisterUserReq) },
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				return handler.(GS_PROJECT_NAMEServiceHandler).RegisterUser(ctx, args[0].(*RegisterUserReq))
			},
		},
		{
			Name:        "UpgradeUser",
			ReqInitFunc: func() interface{} { return new(UpgradeUserReq) },
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				return handler.(GS_PROJECT_NAMEServiceHandler).UpgradeUser(ctx, args[0].(*UpgradeUserReq))
			},
		},
	},
}
