spring.gateway.server.addr=:9440

spring.gateway.routes.api.predicates.path=/api/**
spring.gateway.routes.api.filters=stripPrefix(1),addRequestHeader(X-From,gw)
spring.gateway.routes.api.upstream.target=http://127.0.0.1:19000
