// Code generated by protoc-gen-go (mirrored). DO NOT EDIT.

package svc

import (
	"context"
	"fmt"
)

// PingReq is the request for GS_PROJECT_NAMEService.Ping.
type PingReq struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func NewPingReq() *PingReq { return &PingReq{} }

func (p *PingReq) GetName() (v string) { return p.Name }
func (p *PingReq) SetName(val string)  { p.Name = val }
func (p *PingReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PingReq(%+v)", *p)
}

// PingResp is the response for GS_PROJECT_NAMEService.Ping.
type PingResp struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func NewPingResp() *PingResp { return &PingResp{} }

func (p *PingResp) GetMessage() (v string) { return p.Message }
func (p *PingResp) SetMessage(val string)  { p.Message = val }
func (p *PingResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PingResp(%+v)", *p)
}

// Order is the shared order model exchanged over Kitex/gRPC.
type Order struct {
	ID     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserID string  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Status int32   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
}

func NewOrder() *Order { return &Order{} }

func (p *Order) GetID() (v string)      { return p.ID }
func (p *Order) GetUserID() (v string)  { return p.UserID }
func (p *Order) GetAmount() (v float64) { return p.Amount }
func (p *Order) GetStatus() (v int32)   { return p.Status }
func (p *Order) SetID(val string)       { p.ID = val }
func (p *Order) SetUserID(val string)   { p.UserID = val }
func (p *Order) SetAmount(val float64)  { p.Amount = val }
func (p *Order) SetStatus(val int32)    { p.Status = val }
func (p *Order) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Order(%+v)", *p)
}

// CreateOrderReq is the request for GS_PROJECT_NAMEService.CreateOrder.
type CreateOrderReq struct {
	ID     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserID string  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func NewCreateOrderReq() *CreateOrderReq { return &CreateOrderReq{} }

func (p *CreateOrderReq) GetID() (v string)      { return p.ID }
func (p *CreateOrderReq) GetUserID() (v string)  { return p.UserID }
func (p *CreateOrderReq) GetAmount() (v float64) { return p.Amount }
func (p *CreateOrderReq) SetID(val string)       { p.ID = val }
func (p *CreateOrderReq) SetUserID(val string)   { p.UserID = val }
func (p *CreateOrderReq) SetAmount(val float64)  { p.Amount = val }
func (p *CreateOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderReq(%+v)", *p)
}

// OrderResp is the response for order-domain methods.
type OrderResp struct {
	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *Order `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func NewOrderResp() *OrderResp { return &OrderResp{} }

func (p *OrderResp) GetCode() (v int32)     { return p.Code }
func (p *OrderResp) GetMessage() (v string) { return p.Message }
func (p *OrderResp) GetData() (v *Order)    { return p.Data }
func (p *OrderResp) SetCode(val int32)      { p.Code = val }
func (p *OrderResp) SetMessage(val string)  { p.Message = val }
func (p *OrderResp) SetData(val *Order)     { p.Data = val }
func (p *OrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderResp(%+v)", *p)
}

// PayOrderReq is the request for GS_PROJECT_NAMEService.PayOrder.
type PayOrderReq struct {
	ID string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func NewPayOrderReq() *PayOrderReq { return &PayOrderReq{} }

func (p *PayOrderReq) GetID() (v string) { return p.ID }
func (p *PayOrderReq) SetID(val string)  { p.ID = val }
func (p *PayOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PayOrderReq(%+v)", *p)
}

// ShipOrderReq is the request for GS_PROJECT_NAMEService.ShipOrder.
type ShipOrderReq struct {
	ID string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func NewShipOrderReq() *ShipOrderReq { return &ShipOrderReq{} }

func (p *ShipOrderReq) GetID() (v string) { return p.ID }
func (p *ShipOrderReq) SetID(val string)  { p.ID = val }
func (p *ShipOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ShipOrderReq(%+v)", *p)
}

// User is the shared user model exchanged over Kitex/gRPC.
type User struct {
	ID    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Level int32  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
}

func NewUser() *User { return &User{} }

func (p *User) GetID() (v string)    { return p.ID }
func (p *User) GetName() (v string)  { return p.Name }
func (p *User) GetEmail() (v string) { return p.Email }
func (p *User) GetLevel() (v int32)  { return p.Level }
func (p *User) SetID(val string)     { p.ID = val }
func (p *User) SetName(val string)   { p.Name = val }
func (p *User) SetEmail(val string)  { p.Email = val }
func (p *User) SetLevel(val int32)   { p.Level = val }
func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

// RegisterUserReq is the request for GS_PROJECT_NAMEService.RegisterUser.
type RegisterUserReq struct {
	ID    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func NewRegisterUserReq() *RegisterUserReq { return &RegisterUserReq{} }

func (p *RegisterUserReq) GetID() (v string)    { return p.ID }
func (p *RegisterUserReq) GetName() (v string)  { return p.Name }
func (p *RegisterUserReq) GetEmail() (v string) { return p.Email }
func (p *RegisterUserReq) SetID(val string)     { p.ID = val }
func (p *RegisterUserReq) SetName(val string)   { p.Name = val }
func (p *RegisterUserReq) SetEmail(val string)  { p.Email = val }
func (p *RegisterUserReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterUserReq(%+v)", *p)
}

// UserResp is the response for user-domain methods.
type UserResp struct {
	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *User  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func NewUserResp() *UserResp { return &UserResp{} }

func (p *UserResp) GetCode() (v int32)     { return p.Code }
func (p *UserResp) GetMessage() (v string) { return p.Message }
func (p *UserResp) GetData() (v *User)     { return p.Data }
func (p *UserResp) SetCode(val int32)      { p.Code = val }
func (p *UserResp) SetMessage(val string)  { p.Message = val }
func (p *UserResp) SetData(val *User)      { p.Data = val }
func (p *UserResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserResp(%+v)", *p)
}

// UpgradeUserReq is the request for GS_PROJECT_NAMEService.UpgradeUser.
type UpgradeUserReq struct {
	ID string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func NewUpgradeUserReq() *UpgradeUserReq { return &UpgradeUserReq{} }

func (p *UpgradeUserReq) GetID() (v string) { return p.ID }
func (p *UpgradeUserReq) SetID(val string)  { p.ID = val }
func (p *UpgradeUserReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpgradeUserReq(%+v)", *p)
}

// GS_PROJECT_NAMEService is the aggregate service exposed over Kitex/gRPC (protobuf).
type GS_PROJECT_NAMEService interface {
	Ping(ctx context.Context, req *PingReq) (r *PingResp, err error)
	CreateOrder(ctx context.Context, req *CreateOrderReq) (r *OrderResp, err error)
	PayOrder(ctx context.Context, req *PayOrderReq) (r *OrderResp, err error)
	ShipOrder(ctx context.Context, req *ShipOrderReq) (r *OrderResp, err error)
	RegisterUser(ctx context.Context, req *RegisterUserReq) (r *UserResp, err error)
	UpgradeUser(ctx context.Context, req *UpgradeUserReq) (r *UserResp, err error)
}

// --- Ping Args/Result ---

type GS_PROJECT_NAMEServicePingArgs struct {
	Req *PingReq `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func NewGS_PROJECT_NAMEServicePingArgs() *GS_PROJECT_NAMEServicePingArgs {
	return &GS_PROJECT_NAMEServicePingArgs{}
}

type GS_PROJECT_NAMEServicePingResult struct {
	Success *PingResp `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
}

func NewGS_PROJECT_NAMEServicePingResult() *GS_PROJECT_NAMEServicePingResult {
	return &GS_PROJECT_NAMEServicePingResult{}
}

// --- CreateOrder Args/Result ---

type GS_PROJECT_NAMEServiceCreateOrderArgs struct {
	Req *CreateOrderReq `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func NewGS_PROJECT_NAMEServiceCreateOrderArgs() *GS_PROJECT_NAMEServiceCreateOrderArgs {
	return &GS_PROJECT_NAMEServiceCreateOrderArgs{}
}

type GS_PROJECT_NAMEServiceCreateOrderResult struct {
	Success *OrderResp `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
}

func NewGS_PROJECT_NAMEServiceCreateOrderResult() *GS_PROJECT_NAMEServiceCreateOrderResult {
	return &GS_PROJECT_NAMEServiceCreateOrderResult{}
}

type GS_PROJECT_NAMEServicePayOrderArgs struct {
	Req *PayOrderReq `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func NewGS_PROJECT_NAMEServicePayOrderArgs() *GS_PROJECT_NAMEServicePayOrderArgs {
	return &GS_PROJECT_NAMEServicePayOrderArgs{}
}

type GS_PROJECT_NAMEServicePayOrderResult struct {
	Success *OrderResp `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
}

func NewGS_PROJECT_NAMEServicePayOrderResult() *GS_PROJECT_NAMEServicePayOrderResult {
	return &GS_PROJECT_NAMEServicePayOrderResult{}
}

type GS_PROJECT_NAMEServiceShipOrderArgs struct {
	Req *ShipOrderReq `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func NewGS_PROJECT_NAMEServiceShipOrderArgs() *GS_PROJECT_NAMEServiceShipOrderArgs {
	return &GS_PROJECT_NAMEServiceShipOrderArgs{}
}

type GS_PROJECT_NAMEServiceShipOrderResult struct {
	Success *OrderResp `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
}

func NewGS_PROJECT_NAMEServiceShipOrderResult() *GS_PROJECT_NAMEServiceShipOrderResult {
	return &GS_PROJECT_NAMEServiceShipOrderResult{}
}

type GS_PROJECT_NAMEServiceRegisterUserArgs struct {
	Req *RegisterUserReq `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func NewGS_PROJECT_NAMEServiceRegisterUserArgs() *GS_PROJECT_NAMEServiceRegisterUserArgs {
	return &GS_PROJECT_NAMEServiceRegisterUserArgs{}
}

type GS_PROJECT_NAMEServiceRegisterUserResult struct {
	Success *UserResp `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
}

func NewGS_PROJECT_NAMEServiceRegisterUserResult() *GS_PROJECT_NAMEServiceRegisterUserResult {
	return &GS_PROJECT_NAMEServiceRegisterUserResult{}
}

type GS_PROJECT_NAMEServiceUpgradeUserArgs struct {
	Req *UpgradeUserReq `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func NewGS_PROJECT_NAMEServiceUpgradeUserArgs() *GS_PROJECT_NAMEServiceUpgradeUserArgs {
	return &GS_PROJECT_NAMEServiceUpgradeUserArgs{}
}

type GS_PROJECT_NAMEServiceUpgradeUserResult struct {
	Success *UserResp `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
}

func NewGS_PROJECT_NAMEServiceUpgradeUserResult() *GS_PROJECT_NAMEServiceUpgradeUserResult {
	return &GS_PROJECT_NAMEServiceUpgradeUserResult{}
}
