spring.nacos.ip-addr=127.0.0.1
spring.nacos.port=8848

spring.nacos.instances.a.ip-addr=127.0.0.1
spring.nacos.instances.a.port=8848
spring.nacos.instances.b.ip-addr=127.0.0.1
spring.nacos.instances.b.port=8848
