// Code generated by gs-mock v0.0.8. DO NOT EDIT.
// Tool: https://github.com/go-spring/gs-mock
// gs mock -o app_mock.go -i 'Server'

package gs_app

import (
	"context"

	"github.com/go-spring/gs-mock/gsmock"
)

// ServerMockImpl is a generated mock implementation of the Server interface.
type ServerMockImpl struct {
	r *gsmock.Manager
}

// NewServerMockImpl creates a new mock instance for Server with the given
// gsmock.Manager. Returns an initialized struct ready for registering mock behavior.
func NewServerMockImpl(r *gsmock.Manager) *ServerMockImpl {
	return &ServerMockImpl{r: r}
}

//go:noinline
func (impl *ServerMockImpl) funcRun() func(ctx context.Context, sig ReadySignal) error {
	return impl.Run
}

// Run calls the registered mock for Run via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *ServerMockImpl) Run(ctx context.Context, sig ReadySignal) error {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcRun(), ctx, sig); ok {
		return gsmock.Unbox1[error](ret)
	}
	panic("no mock code matched for ServerMockImpl.Run")
}

// MockRun returns a Mocker21
// for registering mock behavior of Run with specific parameter and return types.
func (impl *ServerMockImpl) MockRun() *gsmock.Mocker21[context.Context, ReadySignal, error] {
	return gsmock.Method21(impl, impl.funcRun(), impl.r)
}

//go:noinline
func (impl *ServerMockImpl) funcStop() func() error {
	return impl.Stop
}

// Stop calls the registered mock for Stop via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *ServerMockImpl) Stop() error {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcStop()); ok {
		return gsmock.Unbox1[error](ret)
	}
	panic("no mock code matched for ServerMockImpl.Stop")
}

// MockStop returns a Mocker01
// for registering mock behavior of Stop with specific parameter and return types.
func (impl *ServerMockImpl) MockStop() *gsmock.Mocker01[error] {
	return gsmock.Method01(impl, impl.funcStop(), impl.r)
}
