// Code generated by gs-http-gen compiler. DO NOT EDIT.

package proto

import (
	"context"
	"net/http"
)

// GS_PROJECT_NAMEServer defines the interface that service must implement.
type GS_PROJECT_NAMEServer interface {
	// Create order API endpoint
	CreateOrder(context.Context, *CreateOrderReq) *CreateOrderResp
	// Pay order API endpoint
	PayOrder(context.Context, *PayOrderReq) *PayOrderResp
	// Ping API endpoint
	Ping(context.Context, *PingReq) *PingResp
	// Register a new user API endpoint
	RegisterUser(context.Context, *RegisterUserReq) *RegisterUserResp
	// Ship order API endpoint
	ShipOrder(context.Context, *ShipOrderReq) *ShipOrderResp
	// Upgrade a user to VIP level API endpoint
	UpgradeUser(context.Context, *UpgradeUserReq) *UpgradeUserResp
}

// InitRouter registers the service handlers into the given *http.ServeMux.
func InitRouter(mux *http.ServeMux, server GS_PROJECT_NAMEServer) {
	mux.HandleFunc("POST /orders", HandleJSON(server.CreateOrder))
	mux.HandleFunc("POST /orders/{id}/pay", HandleJSON(server.PayOrder))
	mux.HandleFunc("GET /ping", HandleJSON(server.Ping))
	mux.HandleFunc("POST /users", HandleJSON(server.RegisterUser))
	mux.HandleFunc("POST /orders/{id}/ship", HandleJSON(server.ShipOrder))
	mux.HandleFunc("POST /users/{id}/upgrade", HandleJSON(server.UpgradeUser))
}
