/*
 * Copyright 2025 The Go-Spring Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Package StarterHTTPClient wires declarative HTTP clients into the Go-Spring
// container. It is the runtime half of the OpenFeign / @HttpExchange equivalent:
// the call sites are generated by gs-http-gen (they hold only a Target), and
// this starter assembles the process-wide transport those calls dispatch
// through (by replacing httpclt.DoRequest) with service discovery, load
// balancing, resilience and trace propagation already in place — so a
// microservice call no longer means hand-wiring a discovery resolver and a
// circuit breaker per client.
package StarterHTTPClient

import (
	"context"
	"io"
	"net/http"
	"slices"
	"sync"

	"go-spring.org/cloud/experimental/httpx"
	"go-spring.org/cloud/governance"
	"go-spring.org/cloud/governance/resilience"
	"go-spring.org/log"
	"go-spring.org/spring/conf"
	"go-spring.org/spring/gs"
	"go-spring.org/stdlib/errutil"
	"go-spring.org/stdlib/flatten"
	"go-spring.org/stdlib/httpclt"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
)

// clientConfig couples a bound instance name with its Config for the global
// assembler.
type clientConfig struct {
	name string
	cfg  Config
}

func init() {
	// Assemble one process-wide transport and replace httpclt.DoRequest with it.
	// The config is multi-entry (spring.http-client.*), but the transport is
	// single: every entry contributes one route to the shared dispatch transport,
	// keyed by its target (addr or service-name). A generated client therefore
	// only carries a Target, and the runtime routes it through this one
	// transport. The bean is exported as a Rooter so it is instantiated even when
	// nothing autowires it.
	gs.Module(gs.OnProperty("spring.http-client"), func(r gs.BeanProvider, p flatten.Storage) error {
		var cfgs []clientConfig
		if err := conf.BindEach(p, "${spring.http-client}", func(name string, c Config) error {
			cfgs = append(cfgs, clientConfig{name: name, cfg: c})
			return nil
		}); err != nil {
			return err
		}
		r.Provide(installDispatch,
			gs.IndexArg(1, gs.ValueArg(cfgs)),
		).Destroy(destroyDispatch).Export(gs.As[gs.Rooter]()).Caller(1)
		return nil
	})
}

// installDispatch assembles the process-wide dispatch transport (one route per
// configured entry) and replaces httpclt.DoRequest with an implementation that
// routes each request through it. Each entry's transport carries the otelhttp
// base, discovery + load balancing, resilience and any user middleware.
//
// The client is deliberately constructed without a Timeout: per-target timeouts
// belong to the resilience policy of each entry, not to a single process-wide
// hard timeout that would apply to every route.
func installDispatch(ctx *gs.ContextProvider, cfgs []clientConfig) (*dispatchTransport, error) {
	d := &dispatchTransport{routes: make(map[string]http.RoundTripper)}
	for _, cc := range cfgs {
		rt, closeFn, err := assembleTransport(ctx, cc.name, cc.cfg)
		if err != nil {
			return nil, err
		}
		d.routes[routeKey(cc.cfg)] = rt
		if closeFn != nil {
			d.closers = append(d.closers, closeFn)
		}
	}
	client := &http.Client{Transport: d}
	httpclt.DoRequest = func(req *http.Request, meta httpclt.Metadata, fn func(io.Reader) error) (*http.Response, error) {
		resp, err := client.Do(req)
		if err != nil {
			return nil, err
		}
		defer func() { _ = resp.Body.Close() }()
		if err = fn(resp.Body); err != nil {
			return nil, err
		}
		return resp, nil
	}
	log.Infof(ctx.Context, log.TagAppDef, "http client initialized, routes=%d", len(d.routes))
	return d, nil
}

// assembleTransport assembles one entry's RoundTripper: otelhttp base → httpx
// discovery/load-balancing/resilience → user middleware. closeFn (when non-nil)
// releases the discovery watch and resilience executor behind it.
func assembleTransport(ctx *gs.ContextProvider, name string, c Config) (rt http.RoundTripper, closeFn func() error, err error) {
	log.Debugf(ctx.Context, log.TagAppDef, "assembling http transport, addr=%s service-name=%s", c.Addr, c.ServiceName)
	if err = c.validate(); err != nil {
		return nil, nil, err
	}
	// TLS: build the transport's TLS config from the tls.* block. nil means the
	// entry stays on system defaults, so a plain http route is untouched.
	tlsCfg, err := c.TLS.Build()
	if err != nil {
		return nil, nil, errutil.Explain(err, "http-client: entry %q", name)
	}
	var baseTransport http.RoundTripper = http.DefaultTransport
	if tlsCfg != nil {
		t := http.DefaultTransport.(*http.Transport).Clone()
		t.TLSClientConfig = tlsCfg
		baseTransport = t
	}
	var base http.RoundTripper = otelhttp.NewTransport(baseTransport)
	if f := currentBaseFactory(); f != nil {
		if custom := f(name, c); custom != nil {
			base = custom
		}
	}
	resource := httpResourceLabel(c)
	exec, err := governedExecutor(resource)
	if err != nil {
		return nil, nil, err
	}
	tcfg := c.toTransportConfig(base, exec)
	if wrappers := currentTransportWrappers(); len(wrappers) > 0 {
		tcfg.WrapTransport = func(rt http.RoundTripper) http.RoundTripper {
			for _, w := range slices.Backward(wrappers) {
				rt = w(name, c, rt)
			}
			return rt
		}
	}
	rt, closeFn, err = httpx.NewTransport(tcfg)
	if err != nil {
		log.Errorf(ctx.Context, log.TagAppDef, "http-client: create transport failed: %v", err)
		return nil, nil, err
	}
	return rt, closeFn, nil
}

// routeKey returns the dispatch key for an entry: its direct address, or its
// service name when routing through discovery. This is the Target a generated
// client sets, and the value dispatchTransport matches against req.Host.
func routeKey(c Config) string {
	if c.Addr != "" {
		return c.Addr
	}
	return c.ServiceName
}

// httpResourceLabel derives the governance resource label for an http client.
// It is deliberately STABLE across addressing modes: service-name wins whenever
// it is set (discovery mode, or direct mode where it is kept as a pure label),
// and only an entry with no service-name at all falls back to its address. A
// govern rule scoped to "http:<service-name>" therefore keeps matching when the
// entry switches between direct and discovery addressing.
func httpResourceLabel(c Config) string {
	return resilience.ResourceLabel("http", c.ServiceName, c.Addr)
}

// minRequestsFloor is the minimum sample size this starter enforces on an
// error-rate breaker resolved for an http resource. resilience's own zero-value
// floor is 1 — a single failure at a 100% rate trips the breaker immediately,
// which is too hair-trigger for typical http traffic. Unless a govern rule sets
// a HIGHER value explicitly, the starter raises MinRequests to this floor. It
// applies only to policies resolved for http-client resources here in the
// starter; resilience core defaults are untouched, and the consecutive
// strategy is unaffected (MinRequests is an error-rate-only knob).
const minRequestsFloor = 5

// governedExecutor builds the resilience executor for one http resource from
// the centralized governance authority, applying the starter-level
// minRequestsFloor to the resolved policy. It subscribes through the
// governance facade (the same direct-import path starter-dubbo uses) instead of
// the resilience.ExecutorFor seam, because the floor must see the resolved
// policy — a seam executor is opaque to it. With governance off (or
// starter-governance not imported) the armed policy is zero and the executor is
// a transparent pass-through, exactly as with ExecutorFor; hot-reload works the
// same way (governance re-invokes the subscriber, the executor Refreshes).
func governedExecutor(resource string) (resilience.Executor, error) {
	var exec resilience.Executor
	refresh := func(p resilience.Policy) {
		if e := exec; e != nil {
			_ = e.Refresh(floorMinRequests(p))
		}
	}
	p := floorMinRequests(governance.Register(resource, refresh))
	e, err := resilience.NewExecutor(governance.Driver(), p)
	if err != nil {
		return nil, err
	}
	exec = e
	return exec, nil
}

// floorMinRequests raises an error-rate policy's MinRequests to
// minRequestsFloor when unset or lower. A policy that is zero or consecutive
// is returned unchanged.
func floorMinRequests(p resilience.Policy) resilience.Policy {
	if p.ResolvedBreakerStrategy() == resilience.BreakerErrorRate && p.ErrorRateThreshold > 0 && p.MinRequests < minRequestsFloor {
		p.MinRequests = minRequestsFloor
	}
	return p
}

// destroyDispatch releases every route's discovery watch and resilience
// executor by closing the dispatch transport.
func destroyDispatch(d *dispatchTransport) error {
	log.Debugf(context.Background(), log.TagAppDef, "http client destroyed")
	return d.Close()
}

// dispatchTransport routes each request by req.Host to the transport assembled
// for that target. It is the single process-wide transport installed by
// replacing httpclt.DoRequest; Close releases every route's resources.
type dispatchTransport struct {
	mu      sync.RWMutex
	routes  map[string]http.RoundTripper
	closers []func() error
}

func (d *dispatchTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	d.mu.RLock()
	rt := d.routes[req.Host]
	d.mu.RUnlock()
	if rt == nil {
		return nil, errutil.Explain(nil, "http-client: no transport for target %q", req.Host)
	}
	return rt.RoundTrip(req)
}

func (d *dispatchTransport) Close() error {
	for _, closeFn := range d.closers {
		if err := closeFn(); err != nil {
			return err
		}
	}
	return nil
}
