/*
 * Copyright 2025 The Go-Spring Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package main

import (
	"text/template"
)

// tmplFileHeader is a template for the header of a generated Go file.
var tmplFileHeader = template.Must(template.New("").Parse(`
// Code generated by gs-mock {{.ToolVersion}}. DO NOT EDIT.
// Tool: https://github.com/go-spring/gs-mock
// gs mock {{.ToolCommand}}

package {{.Package}}

import (
{{.Imports}}
)`))

// tmplInterface is a template for generating a mock implementation of an interface.
var tmplInterface = template.Must(template.New("").Parse(`
// {{.Name}}MockImpl is a generated mock implementation of the {{.Name}} interface.
type {{.Name}}MockImpl{{.TypeParams}} struct {
	{{.EmbedInterfaces}}
	r *gsmock.Manager
}

// New{{.Name}}MockImpl creates a new mock instance for {{.Name}} with the given
// gsmock.Manager. Returns an initialized struct ready for registering mock behavior.
func New{{.Name}}MockImpl{{.TypeParams}}(r *gsmock.Manager) *{{.Name}}MockImpl{{.TypeParamNames}} {
	return &{{.Name}}MockImpl{{.TypeParamNames}}{r: r}
}
`))

// tmplMethod is a template for generating a mock method implementation.
var tmplMethod = template.Must(template.New("").Parse(`
//go:noinline
func (impl *{{.i.Name}}MockImpl{{.i.TypeParamNames}}) func{{.m.Name}}() func({{.m.Params}}){{.m.ResultTypes}}{
	return impl.{{.m.Name}}
}

// {{.m.Name}} calls the registered mock for {{.m.Name}} via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *{{.i.Name}}MockImpl{{.i.TypeParamNames}}) {{.m.Name}}({{.m.Params}}){{.m.ResultTypes}}{
	if {{if .m.ResultTmplTypes}} ret {{else}} _ {{end}}, ok := gsmock.Invoke(impl.r, impl, impl.func{{.m.Name}}(), {{.m.ParamNames}}); ok {
		return {{if .m.ResultTmplTypes}} gsmock.Unbox{{.m.ResultCount}}{{.m.ResultTmplTypes}}(ret){{end}}
	}
	panic("no mock code matched for {{.i.Name}}MockImpl.{{.m.Name}}")
}

// Mock{{.m.Name}} returns a {{.m.VariadicFlag}}Mocker{{.m.ParamCount}}{{.m.ResultCount}}
// for registering mock behavior of {{.m.Name}} with specific parameter and return types.
func (impl *{{.i.Name}}MockImpl{{.i.TypeParamNames}}) Mock{{.m.Name}}() *gsmock.{{.m.VariadicFlag}}Mocker{{.m.ParamCount}}{{.m.ResultCount}}{{.m.MockerTmplTypes}} {
	return gsmock.{{.m.VariadicFlag}}Method{{.m.ParamCount}}{{.m.ResultCount}}(impl, impl.func{{.m.Name}}(), impl.r)
}
`))
