// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: service.proto

// NOTE: the file descriptor byte blobs (file_service_proto_rawDesc, msgTypes,
// depIdxs, TypeBuilder init) that a real protoc-gen-go run would emit are
// intentionally elided from this scaffold. The message structs, their String /
// Reset / ProtoMessage stubs, and the Get* accessors below match the shape of
// generated code so callers can be written against them; when the project is
// materialised the file is regenerated from service.proto and the descriptor
// tables are restored.

package pb

import (
	"fmt"
)

// Envelope is the wire format for every message exchanged on the kratos-ws
// endpoint. Type distinguishes commands; Payload is opaque bytes decoded by the
// receiver based on Type.
type Envelope struct {
	Type    string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Envelope) Reset()         { *x = Envelope{} }
func (x *Envelope) String() string { return fmt.Sprintf("%+v", *x) }
func (*Envelope) ProtoMessage()    {}

func (x *Envelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// EchoPayload is the payload for Envelope{Type:"echo"}: the connection echoes
// Message back with the same Seq so clients can correlate.
type EchoPayload struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Seq     int64  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *EchoPayload) Reset()         { *x = EchoPayload{} }
func (x *EchoPayload) String() string { return fmt.Sprintf("%+v", *x) }
func (*EchoPayload) ProtoMessage()    {}

func (x *EchoPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoPayload) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}
