// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"context"
	"encoding/json"
	"net/http"

	"GS_PROJECT_MODULE/idl/gozero-rest/types"
)

// GS_PROJECT_NAMELogic is the service surface generated from service.api. It is
// declared here (rather than in a separate svc package) so a single bean can be
// exported to Go-Spring's IoC container and satisfy every route registered by
// RegisterHandlers below.
type GS_PROJECT_NAMELogic interface {
	Ping(ctx context.Context, req *types.PingReq) (*types.PingResp, error)
	CreateOrder(ctx context.Context, req *types.CreateOrderReq) (*types.OrderResp, error)
	PayOrder(ctx context.Context, req *types.PayOrderReq) (*types.OrderResp, error)
	ShipOrder(ctx context.Context, req *types.ShipOrderReq) (*types.OrderResp, error)
	RegisterUser(ctx context.Context, req *types.RegisterUserReq) (*types.UserResp, error)
	UpgradeUser(ctx context.Context, req *types.UpgradeUserReq) (*types.UserResp, error)
}

// RegisterHandlers wires the six generated routes onto the supplied ServeMux.
// The Go 1.22+ method+path pattern syntax stands in for goctl's rest.Route
// slice; each entry decodes the request into the goctl-generated types.* struct
// and dispatches to the corresponding method on logic.
func RegisterHandlers(mux *http.ServeMux, logic GS_PROJECT_NAMELogic) {
	mux.HandleFunc("GET /ping", func(w http.ResponseWriter, r *http.Request) {
		req := &types.PingReq{Name: r.URL.Query().Get("name")}
		resp, err := logic.Ping(r.Context(), req)
		writeJSON(w, resp, err)
	})

	mux.HandleFunc("POST /orders", func(w http.ResponseWriter, r *http.Request) {
		req := &types.CreateOrderReq{}
		if err := decodeJSON(r, req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		resp, err := logic.CreateOrder(r.Context(), req)
		writeJSON(w, resp, err)
	})

	mux.HandleFunc("POST /orders/{id}/pay", func(w http.ResponseWriter, r *http.Request) {
		req := &types.PayOrderReq{Id: r.PathValue("id")}
		resp, err := logic.PayOrder(r.Context(), req)
		writeJSON(w, resp, err)
	})

	mux.HandleFunc("POST /orders/{id}/ship", func(w http.ResponseWriter, r *http.Request) {
		req := &types.ShipOrderReq{Id: r.PathValue("id")}
		resp, err := logic.ShipOrder(r.Context(), req)
		writeJSON(w, resp, err)
	})

	mux.HandleFunc("POST /users", func(w http.ResponseWriter, r *http.Request) {
		req := &types.RegisterUserReq{}
		if err := decodeJSON(r, req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		resp, err := logic.RegisterUser(r.Context(), req)
		writeJSON(w, resp, err)
	})

	mux.HandleFunc("POST /users/{id}/upgrade", func(w http.ResponseWriter, r *http.Request) {
		req := &types.UpgradeUserReq{Id: r.PathValue("id")}
		resp, err := logic.UpgradeUser(r.Context(), req)
		writeJSON(w, resp, err)
	})
}

// decodeJSON parses an incoming JSON body into out. goctl-generated code would
// normally use httpx.Parse to fold path/form/json into a single struct; the
// template keeps a minimal stub so the file remains compilable in spirit.
func decodeJSON(r *http.Request, out any) error {
	// TODO: replace with a proper httpx.Parse-style decoder that also folds
	// path/form parameters into out.
	if r.Body == nil {
		return nil
	}
	defer r.Body.Close()
	return json.NewDecoder(r.Body).Decode(out)
}

// writeJSON serializes resp as JSON, or writes a 500 with err.Error when err is
// non-nil. goctl produces the same shape via httpx.OkJson / httpx.ErrorCtx.
func writeJSON(w http.ResponseWriter, resp any, err error) {
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(resp)
}
