// Code generated by Kitex v0.16.3. DO NOT EDIT.
package echoservice

import (
	server "github.com/cloudwego/kitex/server"
	echo "go-spring.org/kitex/generic/idl/echo"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler echo.EchoService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler echo.EchoService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
