
		server.addr=0.0.0.0:9090
		
		log.access.name=access.log
		log.access.dir=./log
		
		log.biz.name=biz.log
		log.biz.dir=./log
		
		log.dao.name=dao.log
		log.dao.dir=./log
		
		refresh_time=1756597178108
	