// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// 	protoc-gen-go-http v0.1.0 (scaffold)
// 	protoc             v5.27.0
// source: service.proto

// NOTE: unlike protoc-gen-go-grpc, there is no single canonical HTTP codegen
// plugin — the shape below (server interface + registrar) mirrors the gRPC
// scaffold so the goframe HTTP server can bind the same controller matrix. The
// registrar receives the goframe router (`s any`) and would iterate over each
// rpc to mount it as POST /GS_PROJECT_NAMEService/<Method>. The scaffold keeps
// the package dependency-free.

package pb

import (
	"context"
	"errors"
)

// GS_PROJECT_NAMEServer is the server API for GS_PROJECT_NAMEService when it
// is exposed over HTTP via the goframe router.
//
// All implementations should embed UnimplementedGS_PROJECT_NAMEServer for
// forward compatibility with new rpcs.
type GS_PROJECT_NAMEServer interface {
	Ping(context.Context, *PingReq) (*PingResp, error)
	CreateOrder(context.Context, *CreateOrderReq) (*OrderResp, error)
	PayOrder(context.Context, *PayOrderReq) (*OrderResp, error)
	ShipOrder(context.Context, *ShipOrderReq) (*OrderResp, error)
	RegisterUser(context.Context, *RegisterUserReq) (*UserResp, error)
	UpgradeUser(context.Context, *UpgradeUserReq) (*UserResp, error)
}

// UnimplementedGS_PROJECT_NAMEServer should be embedded to have forward
// compatible implementations.
type UnimplementedGS_PROJECT_NAMEServer struct{}

func (UnimplementedGS_PROJECT_NAMEServer) Ping(context.Context, *PingReq) (*PingResp, error) {
	return nil, errors.New("method Ping not implemented")
}

func (UnimplementedGS_PROJECT_NAMEServer) CreateOrder(context.Context, *CreateOrderReq) (*OrderResp, error) {
	return nil, errors.New("method CreateOrder not implemented")
}

func (UnimplementedGS_PROJECT_NAMEServer) PayOrder(context.Context, *PayOrderReq) (*OrderResp, error) {
	return nil, errors.New("method PayOrder not implemented")
}

func (UnimplementedGS_PROJECT_NAMEServer) ShipOrder(context.Context, *ShipOrderReq) (*OrderResp, error) {
	return nil, errors.New("method ShipOrder not implemented")
}

func (UnimplementedGS_PROJECT_NAMEServer) RegisterUser(context.Context, *RegisterUserReq) (*UserResp, error) {
	return nil, errors.New("method RegisterUser not implemented")
}

func (UnimplementedGS_PROJECT_NAMEServer) UpgradeUser(context.Context, *UpgradeUserReq) (*UserResp, error) {
	return nil, errors.New("method UpgradeUser not implemented")
}

// RegisterGS_PROJECT_NAMEServer mounts the service implementation on the goframe
// HTTP router.
//
// In real generated code s is *ghttp.Server (or a group router) and this call
// registers one POST route per rpc. The scaffold stubs out the registration so
// the pb package keeps zero external deps; the call site in goframehttpsvr.go
// passes the goframe router here once the real dep is added.
func RegisterGS_PROJECT_NAMEServer(s any, srv GS_PROJECT_NAMEServer) {
	// TODO: s.(*ghttp.Server).Group("/GS_PROJECT_NAMEService", func(g *ghttp.RouterGroup){ ... })
	_ = s
	_ = srv
}
