// Code generated by trpc-cmdline. DO NOT EDIT.
// versions:
// 	trpc-cmdline latest
// source: service.proto

// NOTE: the real trpc-cmdline output imports trpc.group/trpc-go/trpc-go for
// server.Service registration and the service descriptor. The scaffold keeps
// this package dependency-free: the registrar is modelled as `any`, the
// service descriptor is elided, and Unimplemented* returns a plain Go error.
// When the project is materialised the file is regenerated against real trpc.

package pb

import (
	"context"
	"errors"
)

// GS_PROJECT_NAMEService_ServiceName is the fully-qualified service name.
const GS_PROJECT_NAMEService_ServiceName = "trpc.GS_PROJECT_NAMEService"

// GS_PROJECT_NAMEService is the server API for GS_PROJECT_NAMEService.
//
// All implementations should embed UnimplementedGS_PROJECT_NAMEService for
// forward compatibility with new rpcs.
type GS_PROJECT_NAMEService interface {
	Ping(context.Context, *PingReq) (*PingResp, error)
	CreateOrder(context.Context, *CreateOrderReq) (*OrderResp, error)
	PayOrder(context.Context, *PayOrderReq) (*OrderResp, error)
	ShipOrder(context.Context, *ShipOrderReq) (*OrderResp, error)
	RegisterUser(context.Context, *RegisterUserReq) (*UserResp, error)
	UpgradeUser(context.Context, *UpgradeUserReq) (*UserResp, error)
}

// UnimplementedGS_PROJECT_NAMEService should be embedded to have forward
// compatible implementations.
type UnimplementedGS_PROJECT_NAMEService struct{}

func (UnimplementedGS_PROJECT_NAMEService) Ping(context.Context, *PingReq) (*PingResp, error) {
	return nil, errors.New("method Ping not implemented")
}

func (UnimplementedGS_PROJECT_NAMEService) CreateOrder(context.Context, *CreateOrderReq) (*OrderResp, error) {
	return nil, errors.New("method CreateOrder not implemented")
}

func (UnimplementedGS_PROJECT_NAMEService) PayOrder(context.Context, *PayOrderReq) (*OrderResp, error) {
	return nil, errors.New("method PayOrder not implemented")
}

func (UnimplementedGS_PROJECT_NAMEService) ShipOrder(context.Context, *ShipOrderReq) (*OrderResp, error) {
	return nil, errors.New("method ShipOrder not implemented")
}

func (UnimplementedGS_PROJECT_NAMEService) RegisterUser(context.Context, *RegisterUserReq) (*UserResp, error) {
	return nil, errors.New("method RegisterUser not implemented")
}

func (UnimplementedGS_PROJECT_NAMEService) UpgradeUser(context.Context, *UpgradeUserReq) (*UserResp, error) {
	return nil, errors.New("method UpgradeUser not implemented")
}

// RegisterGS_PROJECT_NAMEService registers the service implementation with the
// given tRPC service registrar.
//
// In real generated code s is server.Service and this call invokes
// s.Register(&GS_PROJECT_NAMEService_ServiceDesc, svr). The scaffold stubs out
// the registration so the pb package keeps zero external deps; the call site
// in trpcsvr.go passes the real trpc server.Service here once the dep is added.
func RegisterGS_PROJECT_NAMEService(s any, svr GS_PROJECT_NAMEService) {
	// TODO: s.(server.Service).Register(&GS_PROJECT_NAMEService_ServiceDesc, svr)
	_ = s
	_ = svr
}
