spring.elasticsearch.docs.addresses=http://127.0.0.1:9200
spring.elasticsearch.docs.driver=AnotherESDriver

spring.elasticsearch.logs.addresses=http://127.0.0.1:9200
spring.elasticsearch.logs.driver=AnotherESDriver
