spring.memcached.cache.servers=127.0.0.1:11211
spring.memcached.cache.driver=AnotherMemcachedDriver

spring.memcached.session.servers=127.0.0.1:11211
spring.memcached.session.driver=AnotherMemcachedDriver
