// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package echo

import (
	"context"
	"fmt"
)

type EchoRequest struct {
	Message string `thrift:"message,1,required" frugal:"1,required,string" json:"message"`
}

func NewEchoRequest() *EchoRequest {
	return &EchoRequest{}
}

func (p *EchoRequest) InitDefault() {
}

func (p *EchoRequest) GetMessage() (v string) {
	return p.Message
}
func (p *EchoRequest) SetMessage(val string) {
	p.Message = val
}

func (p *EchoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoRequest(%+v)", *p)
}

var fieldIDToName_EchoRequest = map[int16]string{
	1: "message",
}

type EchoResponse struct {
	Message string `thrift:"message,1,required" frugal:"1,required,string" json:"message"`
}

func NewEchoResponse() *EchoResponse {
	return &EchoResponse{}
}

func (p *EchoResponse) InitDefault() {
}

func (p *EchoResponse) GetMessage() (v string) {
	return p.Message
}
func (p *EchoResponse) SetMessage(val string) {
	p.Message = val
}

func (p *EchoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoResponse(%+v)", *p)
}

var fieldIDToName_EchoResponse = map[int16]string{
	1: "message",
}

type EchoService interface {
	Echo(ctx context.Context, req *EchoRequest) (r *EchoResponse, err error)
}

type EchoServiceEchoArgs struct {
	Req *EchoRequest `thrift:"req,1" frugal:"1,default,EchoRequest" json:"req"`
}

func NewEchoServiceEchoArgs() *EchoServiceEchoArgs {
	return &EchoServiceEchoArgs{}
}

func (p *EchoServiceEchoArgs) InitDefault() {
}

var EchoServiceEchoArgs_Req_DEFAULT *EchoRequest

func (p *EchoServiceEchoArgs) GetReq() (v *EchoRequest) {
	if !p.IsSetReq() {
		return EchoServiceEchoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *EchoServiceEchoArgs) SetReq(val *EchoRequest) {
	p.Req = val
}

func (p *EchoServiceEchoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EchoServiceEchoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoServiceEchoArgs(%+v)", *p)
}

var fieldIDToName_EchoServiceEchoArgs = map[int16]string{
	1: "req",
}

type EchoServiceEchoResult struct {
	Success *EchoResponse `thrift:"success,0,optional" frugal:"0,optional,EchoResponse" json:"success,omitempty"`
}

func NewEchoServiceEchoResult() *EchoServiceEchoResult {
	return &EchoServiceEchoResult{}
}

func (p *EchoServiceEchoResult) InitDefault() {
}

var EchoServiceEchoResult_Success_DEFAULT *EchoResponse

func (p *EchoServiceEchoResult) GetSuccess() (v *EchoResponse) {
	if !p.IsSetSuccess() {
		return EchoServiceEchoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *EchoServiceEchoResult) SetSuccess(x interface{}) {
	p.Success = x.(*EchoResponse)
}

func (p *EchoServiceEchoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoServiceEchoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoServiceEchoResult(%+v)", *p)
}

var fieldIDToName_EchoServiceEchoResult = map[int16]string{
	0: "success",
}
