// Code generated by gs-http-gen compiler. DO NOT EDIT.

package proto

import (
	"context"
	"fmt"
	"net/http"

	"go-spring.org/spring/web/httpclt"
)

// Client represents an HTTP client bound to a specific service endpoint.
//
// Target identifies the remote service, which can be either a service name
// (for service discovery) or a direct address in the form of "IP:PORT".
//
// HTTPClient carries the transport every call runs on. Leave it nil to use
// http.DefaultClient, or inject an *http.Client whose Transport adds service
// discovery, load balancing and resilience (see go-spring.org/spring/httpx and
// starter-http-client) — the generated call sites are unchanged either way.
type Client struct {
	Target     string
	HTTPClient *http.Client
}

// Create a new manager
func (c *Client) CreateManager(ctx context.Context, req *CreateManagerReq, opts ...httpclt.RequestOption) (*http.Response, *CreateManagerResp, error) {
	meta := httpclt.CombineMetadata(httpclt.Metadata{
		Target:  c.Target,
		Client:  c.HTTPClient,
		Schema:  "http",
		Method:  "POST",
		Pattern: "/managers",
		RawPath: fmt.Sprintf("/managers"),
		Query:   req,
		Body:    &req.CreateManagerReqBody,
		Header:  http.Header{"Content-Type": []string{"application/json"}},
	}, opts...)
	return httpclt.ObjectResponse(ctx, NewCreateManagerResp(), meta)
}

// Delete manager
func (c *Client) DeleteManager(ctx context.Context, req *GetManagerReq, opts ...httpclt.RequestOption) (*http.Response, *DeleteManagerResp, error) {
	meta := httpclt.CombineMetadata(httpclt.Metadata{
		Target:  c.Target,
		Client:  c.HTTPClient,
		Schema:  "http",
		Method:  "DELETE",
		Pattern: "/managers/{id}",
		RawPath: fmt.Sprintf("/managers/%v", req.Id),
		Query:   req,
		Body:    &req.GetManagerReqBody,
		Header:  http.Header{"Content-Type": []string{"application/x-www-form-urlencoded"}},
	}, opts...)
	return httpclt.ObjectResponse(ctx, NewDeleteManagerResp(), meta)
}

// Get manager by ID
func (c *Client) GetManager(ctx context.Context, req *GetManagerReq, opts ...httpclt.RequestOption) (*http.Response, *GetManagerResp, error) {
	meta := httpclt.CombineMetadata(httpclt.Metadata{
		Target:  c.Target,
		Client:  c.HTTPClient,
		Schema:  "http",
		Method:  "GET",
		Pattern: "/managers/{id}",
		RawPath: fmt.Sprintf("/managers/%v", req.Id),
		Query:   req,
		Body:    &req.GetManagerReqBody,
		Header:  http.Header{"Content-Type": []string{"application/x-www-form-urlencoded"}},
	}, opts...)
	return httpclt.ObjectResponse(ctx, NewGetManagerResp(), meta)
}

// List managers with pagination
func (c *Client) ListManagers(ctx context.Context, req *ListManagersReq, opts ...httpclt.RequestOption) (*http.Response, *ListManagersResp, error) {
	meta := httpclt.CombineMetadata(httpclt.Metadata{
		Target:  c.Target,
		Client:  c.HTTPClient,
		Schema:  "http",
		Method:  "GET",
		Pattern: "/managers",
		RawPath: fmt.Sprintf("/managers"),
		Query:   req,
		Body:    &req.ListManagersReqBody,
		Header:  http.Header{"Content-Type": []string{"application/x-www-form-urlencoded"}},
	}, opts...)
	return httpclt.ObjectResponse(ctx, NewListManagersResp(), meta)
}

// Update manager
func (c *Client) UpdateManager(ctx context.Context, req *UpdateManagerReq, opts ...httpclt.RequestOption) (*http.Response, *UpdateManagerResp, error) {
	meta := httpclt.CombineMetadata(httpclt.Metadata{
		Target:  c.Target,
		Client:  c.HTTPClient,
		Schema:  "http",
		Method:  "PUT",
		Pattern: "/managers/{id}",
		RawPath: fmt.Sprintf("/managers/%v", req.Id),
		Query:   req,
		Body:    &req.UpdateManagerReqBody,
		Header:  http.Header{"Content-Type": []string{"application/json"}},
	}, opts...)
	return httpclt.ObjectResponse(ctx, NewUpdateManagerResp(), meta)
}
