// Code generated by gs-http-gen compiler. DO NOT EDIT.

package proto

import (
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"go-spring.org/stdlib/errutil"
	"go-spring.org/stdlib/formutil"
	"go-spring.org/stdlib/hashutil"
	"go-spring.org/stdlib/httpsvr"
	"go-spring.org/stdlib/jsonflow"
)

var _ = strings.Index
var _ = url.ParseQuery
var _ = strconv.FormatInt
var _ = base64.StdEncoding
var _ = http.StatusNotFound
var _ = (*httpsvr.Router)(nil)
var _ = formutil.EncodeInt[int]

const MIN_AGE int64 = 18

const MAX_AGE int64 = 150

const DEFAULT_PAGE int64 = 1

const DEFAULT_PAGE_SIZE int64 = 20

const MAX_PAGE_SIZE int64 = 100

const SALARY_MIN float64 = 0.0

const SALARY_MAX float64 = 1000000.0

// Standard error codes
type ErrCode int32

const (
	ErrCode_ERR_OK            ErrCode = 0
	ErrCode_PARAM_ERROR       ErrCode = 1003
	ErrCode_NOT_FOUND         ErrCode = 4004
	ErrCode_PERMISSION_DENIED ErrCode = 4003
	ErrCode_INTERNAL_ERROR    ErrCode = 5000
)

var (
	ErrCode_name = map[ErrCode]string{
		0:    "ERR_OK",
		1003: "PARAM_ERROR",
		4004: "NOT_FOUND",
		4003: "PERMISSION_DENIED",
		5000: "INTERNAL_ERROR",
	}
	ErrCode_value = map[string]ErrCode{
		"ERR_OK":            0,
		"PARAM_ERROR":       1003,
		"NOT_FOUND":         4004,
		"PERMISSION_DENIED": 4003,
		"INTERNAL_ERROR":    5000,
	}
	ErrCode_message = map[ErrCode]string{
		0:    "ERR_OK",
		1003: "param error",
		4004: "NOT_FOUND",
		4003: "PERMISSION_DENIED",
		5000: "INTERNAL_ERROR",
	}
)

// OneOfErrCode reports whether it's a valid ErrCode.
func OneOfErrCode(i ErrCode) bool {
	_, ok := ErrCode_name[i]
	return ok
}

// OneOfErrCodeAsString reports whether it's a valid ErrCodeAsString.
func OneOfErrCodeAsString(i ErrCodeAsString) bool {
	_, ok := ErrCode_name[ErrCode(i)]
	return ok
}

// ErrCodeAsString wraps ErrCode to encode/decode as a JSON string.
type ErrCodeAsString ErrCode

// MarshalJSON encodes the enum value as its string name.
func (x ErrCodeAsString) MarshalJSON() ([]byte, error) {
	if s, ok := ErrCode_name[ErrCode(x)]; ok {
		return []byte(fmt.Sprintf("\"%s\"", s)), nil
	}
	return nil, errutil.Explain(nil, "invalid ErrCodeAsString: %d", x)
}

// UnmarshalJSON decodes the enum value from its string name.
func (x *ErrCodeAsString) UnmarshalJSON(data []byte) error {
	str := strings.Trim(string(data), "\"")
	if v, ok := ErrCode_value[str]; ok {
		*x = ErrCodeAsString(v)
		return nil
	}
	return errutil.Explain(nil, "invalid ErrCodeAsString value: %q", str)
}

// Manager seniority level
type ManagerLevel int32

const (
	ManagerLevel_JUNIOR ManagerLevel = 1
	ManagerLevel_MIDDLE ManagerLevel = 2
	ManagerLevel_SENIOR ManagerLevel = 3
)

var (
	ManagerLevel_name = map[ManagerLevel]string{
		1: "JUNIOR",
		2: "MIDDLE",
		3: "SENIOR",
	}
	ManagerLevel_value = map[string]ManagerLevel{
		"JUNIOR": 1,
		"MIDDLE": 2,
		"SENIOR": 3,
	}
)

// OneOfManagerLevel reports whether it's a valid ManagerLevel.
func OneOfManagerLevel(i ManagerLevel) bool {
	_, ok := ManagerLevel_name[i]
	return ok
}

// OneOfManagerLevelAsString reports whether it's a valid ManagerLevelAsString.
func OneOfManagerLevelAsString(i ManagerLevelAsString) bool {
	_, ok := ManagerLevel_name[ManagerLevel(i)]
	return ok
}

// ManagerLevelAsString wraps ManagerLevel to encode/decode as a JSON string.
type ManagerLevelAsString ManagerLevel

// MarshalJSON encodes the enum value as its string name.
func (x ManagerLevelAsString) MarshalJSON() ([]byte, error) {
	if s, ok := ManagerLevel_name[ManagerLevel(x)]; ok {
		return []byte(fmt.Sprintf("\"%s\"", s)), nil
	}
	return nil, errutil.Explain(nil, "invalid ManagerLevelAsString: %d", x)
}

// UnmarshalJSON decodes the enum value from its string name.
func (x *ManagerLevelAsString) UnmarshalJSON(data []byte) error {
	str := strings.Trim(string(data), "\"")
	if v, ok := ManagerLevel_value[str]; ok {
		*x = ManagerLevelAsString(v)
		return nil
	}
	return errutil.Explain(nil, "invalid ManagerLevelAsString value: %q", str)
}

// Company departments
type Department int32

const (
	Department_ENGINEERING Department = 1
	Department_MARKETING   Department = 2
	Department_SALES       Department = 3
	Department_HR          Department = 4
	Department_FINANCE     Department = 5
)

var (
	Department_name = map[Department]string{
		1: "ENGINEERING",
		2: "MARKETING",
		3: "SALES",
		4: "HR",
		5: "FINANCE",
	}
	Department_value = map[string]Department{
		"ENGINEERING": 1,
		"MARKETING":   2,
		"SALES":       3,
		"HR":          4,
		"FINANCE":     5,
	}
)

// OneOfDepartment reports whether it's a valid Department.
func OneOfDepartment(i Department) bool {
	_, ok := Department_name[i]
	return ok
}

// OneOfDepartmentAsString reports whether it's a valid DepartmentAsString.
func OneOfDepartmentAsString(i DepartmentAsString) bool {
	_, ok := Department_name[Department(i)]
	return ok
}

// DepartmentAsString wraps Department to encode/decode as a JSON string.
type DepartmentAsString Department

// MarshalJSON encodes the enum value as its string name.
func (x DepartmentAsString) MarshalJSON() ([]byte, error) {
	if s, ok := Department_name[Department(x)]; ok {
		return []byte(fmt.Sprintf("\"%s\"", s)), nil
	}
	return nil, errutil.Explain(nil, "invalid DepartmentAsString: %d", x)
}

// UnmarshalJSON decodes the enum value from its string name.
func (x *DepartmentAsString) UnmarshalJSON(data []byte) error {
	str := strings.Trim(string(data), "\"")
	if v, ok := Department_value[str]; ok {
		*x = DepartmentAsString(v)
		return nil
	}
	return errutil.Explain(nil, "invalid DepartmentAsString value: %q", str)
}

// Pagination request
type PageReq struct {
	Page int64 `json:"page" query:"page" validate:"required"`
	Size int64 `json:"size" query:"size" validate:"required"`
}

// NewPageReq creates a new PageReq instance
// and initializes fields with default values.
func NewPageReq() *PageReq {
	return &PageReq{}
}

// DecodeJSON decodes a JSON object into PageReq using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *PageReq) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashPage = 0x38b2a0deba58916  // HashKey("page")
		hashSize = 0x4dea9618e618ae3c // HashKey("size")
	)

	var (
		hasPage bool
		hasSize bool
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashPage:
			if key != "page" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			hasPage = true
			if r.Page, err = jsonflow.DecodeInt[int64](d); err != nil {
				return err
			}

		case hashSize:
			if key != "size" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			hasSize = true
			if r.Size, err = jsonflow.DecodeInt[int64](d); err != nil {
				return err
			}

		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}

	if !hasPage {
		return errutil.Explain(err, "missing required field \"page\"")
	}
	if !hasSize {
		return errutil.Explain(err, "missing required field \"size\"")
	}
	return
}

// EncodeJSON encodes PageReq into a JSON object using streaming
// token writes.
func (x *PageReq) EncodeJSON(e jsonflow.Encoder) error {
	if x == nil {
		return jsonflow.EncodeNull(e)
	}
	if err := e.WriteObjectBegin(); err != nil {
		return err
	}
	if err := e.WriteString("page"); err != nil {
		return err
	}
	if err := jsonflow.EncodeInt[int64](e, x.Page); err != nil {
		return err
	}
	if err := e.WriteString("size"); err != nil {
		return err
	}
	if err := jsonflow.EncodeInt[int64](e, x.Size); err != nil {
		return err
	}
	return e.WriteObjectEnd()
}

// Validate checks field values using generated validation expressions.
func (x *PageReq) Validate() error {
	if !(x.Page >= 1) {
		return errutil.Explain(nil, "validate failed on \"PageReq.Page\"")
	}
	if !(x.Size >= 1 && x.Size <= MAX_PAGE_SIZE) {
		return errutil.Explain(nil, "validate failed on \"PageReq.Size\"")
	}
	return nil
}

type Address struct {
	City       *string `json:"city,omitempty" form:"city"`
	Street     *string `json:"street,omitempty" form:"street"`
	PostalCode *string `json:"postalCode,omitempty" form:"postalCode"`
}

// NewAddress creates a new Address instance
// and initializes fields with default values.
func NewAddress() *Address {
	return &Address{}
}

// DecodeJSON decodes a JSON object into Address using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *Address) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashCity       = 0xf9dab5910f08a8a2 // HashKey("city")
		hashStreet     = 0x4f5c4dd8e884633e // HashKey("street")
		hashPostalCode = 0x95dac24ad2f17db7 // HashKey("postalCode")
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashCity:
			if key != "city" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.City, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashStreet:
			if key != "street" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Street, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashPostalCode:
			if key != "postalCode" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.PostalCode, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}
	return
}

// EncodeJSON encodes Address into a JSON object using streaming
// token writes.
func (x *Address) EncodeJSON(e jsonflow.Encoder) error {
	if x == nil {
		return jsonflow.EncodeNull(e)
	}
	if err := e.WriteObjectBegin(); err != nil {
		return err
	}
	if !(x.City == nil) {
		if err := e.WriteString("city"); err != nil {
			return err
		}
		if err := jsonflow.EncodeStringPtr[string](e, x.City); err != nil {
			return err
		}
	}
	if !(x.Street == nil) {
		if err := e.WriteString("street"); err != nil {
			return err
		}
		if err := jsonflow.EncodeStringPtr[string](e, x.Street); err != nil {
			return err
		}
	}
	if !(x.PostalCode == nil) {
		if err := e.WriteString("postalCode"); err != nil {
			return err
		}
		if err := jsonflow.EncodeStringPtr[string](e, x.PostalCode); err != nil {
			return err
		}
	}
	return e.WriteObjectEnd()
}

type ContactInfo struct {
	Email   string   `json:"email" form:"email" validate:"required"`
	Phone   *string  `json:"phone,omitempty" form:"phone"`
	Address *Address `json:"address,omitempty" form:"address"`
}

// NewContactInfo creates a new ContactInfo instance
// and initializes fields with default values.
func NewContactInfo() *ContactInfo {
	return &ContactInfo{}
}

// DecodeJSON decodes a JSON object into ContactInfo using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *ContactInfo) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashEmail   = 0x123467b419acbc07 // HashKey("email")
		hashPhone   = 0x31fc9c6bde865d6f // HashKey("phone")
		hashAddress = 0x1737f69e334c12b3 // HashKey("address")
	)

	var (
		hasEmail bool
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashEmail:
			if key != "email" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			hasEmail = true
			if r.Email, err = jsonflow.DecodeString(d); err != nil {
				return err
			}

		case hashPhone:
			if key != "phone" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Phone, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashAddress:
			if key != "address" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Address, err = jsonflow.DecodeObject(NewAddress)(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}

	if !hasEmail {
		return errutil.Explain(err, "missing required field \"email\"")
	}
	return
}

// EncodeJSON encodes ContactInfo into a JSON object using streaming
// token writes.
func (x *ContactInfo) EncodeJSON(e jsonflow.Encoder) error {
	if x == nil {
		return jsonflow.EncodeNull(e)
	}
	if err := e.WriteObjectBegin(); err != nil {
		return err
	}
	if err := e.WriteString("email"); err != nil {
		return err
	}
	if err := jsonflow.EncodeString[string](e, x.Email); err != nil {
		return err
	}
	if !(x.Phone == nil) {
		if err := e.WriteString("phone"); err != nil {
			return err
		}
		if err := jsonflow.EncodeStringPtr[string](e, x.Phone); err != nil {
			return err
		}
	}
	if !(x.Address == nil) {
		if err := e.WriteString("address"); err != nil {
			return err
		}
		if err := jsonflow.EncodeObject[*Address](e, x.Address); err != nil {
			return err
		}
	}
	return e.WriteObjectEnd()
}

// Validate checks field values using generated validation expressions.
func (x *ContactInfo) Validate() error {
	if !(Email(x.Email)) {
		return errutil.Explain(nil, "validate failed on \"ContactInfo.Email\"")
	}
	return nil
}

type Manager struct {
	Id         *string               `json:"id,omitempty" form:"id"`
	Name       *string               `json:"name,omitempty" form:"name"`
	Age        *int64                `json:"age,omitempty" form:"age"`
	Vip        *bool                 `json:"vip,omitempty" form:"vip"`
	Salary     *float64              `json:"salary,omitempty" form:"salary"`
	Level      *ManagerLevelAsString `json:"level,omitempty" form:"level"`
	Department *Department           `json:"department,omitempty" form:"department"`
	// Primary contact information
	PrimaryContact *ContactInfo `json:"primaryContact,omitempty" form:"primaryContact"`
	// Additional contacts
	Contacts []*ContactInfo `json:"contacts,omitempty" form:"contacts"`
	// Lightweight extensibility fields
	Tags   map[string]string   `json:"tags,omitempty" form:"tags"`
	Labels map[string][]string `json:"labels,omitempty" form:"labels"`
}

// NewManager creates a new Manager instance
// and initializes fields with default values.
func NewManager() *Manager {
	return &Manager{}
}

// DecodeJSON decodes a JSON object into Manager using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *Manager) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashId             = 0x8b72e07b55c3ac0  // HashKey("id")
		hashName           = 0xc4bcadba8e631b86 // HashKey("name")
		hashAge            = 0xe715b4190539215c // HashKey("age")
		hashVip            = 0x68e906194eba76f0 // HashKey("vip")
		hashSalary         = 0x69c724098dbd2bc3 // HashKey("salary")
		hashLevel          = 0xe8ddc90a9d7c709d // HashKey("level")
		hashDepartment     = 0x9fe2b90fc81732c7 // HashKey("department")
		hashPrimaryContact = 0xb6c6aac71fb849af // HashKey("primaryContact")
		hashContacts       = 0x17f458ee83d31930 // HashKey("contacts")
		hashTags           = 0xd91c3bef076f8580 // HashKey("tags")
		hashLabels         = 0x4bc513f856980a8a // HashKey("labels")
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashId:
			if key != "id" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Id, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashName:
			if key != "name" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Name, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashAge:
			if key != "age" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Age, err = jsonflow.DecodeIntPtr[int64](d); err != nil {
				return err
			}
		case hashVip:
			if key != "vip" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Vip, err = jsonflow.DecodeBoolPtr(d); err != nil {
				return err
			}
		case hashSalary:
			if key != "salary" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Salary, err = jsonflow.DecodeFloatPtr[float64](d); err != nil {
				return err
			}
		case hashLevel:
			if key != "level" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Level, err = jsonflow.DecodeAny[*ManagerLevelAsString](d); err != nil {
				return err
			}
		case hashDepartment:
			if key != "department" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Department, err = jsonflow.DecodeIntPtr[Department](d); err != nil {
				return err
			}
		case hashPrimaryContact:
			if key != "primaryContact" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.PrimaryContact, err = jsonflow.DecodeObject(NewContactInfo)(d); err != nil {
				return err
			}
		case hashContacts:
			if key != "contacts" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Contacts, err = jsonflow.DecodeArray(jsonflow.DecodeObject(NewContactInfo))(d); err != nil {
				return err
			}
		case hashTags:
			if key != "tags" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Tags, err = jsonflow.DecodeMap(jsonflow.DecodeString, jsonflow.DecodeString)(d); err != nil {
				return err
			}
		case hashLabels:
			if key != "labels" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Labels, err = jsonflow.DecodeMap(jsonflow.DecodeString, jsonflow.DecodeArray(jsonflow.DecodeString))(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}
	return
}

// EncodeJSON encodes Manager into a JSON object using streaming
// token writes.
func (x *Manager) EncodeJSON(e jsonflow.Encoder) error {
	if x == nil {
		return jsonflow.EncodeNull(e)
	}
	if err := e.WriteObjectBegin(); err != nil {
		return err
	}
	if !(x.Id == nil) {
		if err := e.WriteString("id"); err != nil {
			return err
		}
		if err := jsonflow.EncodeStringPtr[string](e, x.Id); err != nil {
			return err
		}
	}
	if !(x.Name == nil) {
		if err := e.WriteString("name"); err != nil {
			return err
		}
		if err := jsonflow.EncodeStringPtr[string](e, x.Name); err != nil {
			return err
		}
	}
	if !(x.Age == nil) {
		if err := e.WriteString("age"); err != nil {
			return err
		}
		if err := jsonflow.EncodeIntPtr[int64](e, x.Age); err != nil {
			return err
		}
	}
	if !(x.Vip == nil) {
		if err := e.WriteString("vip"); err != nil {
			return err
		}
		if err := jsonflow.EncodeBoolPtr[bool](e, x.Vip); err != nil {
			return err
		}
	}
	if !(x.Salary == nil) {
		if err := e.WriteString("salary"); err != nil {
			return err
		}
		if err := jsonflow.EncodeFloatPtr[float64](e, x.Salary); err != nil {
			return err
		}
	}
	if !(x.Level == nil) {
		if err := e.WriteString("level"); err != nil {
			return err
		}
		if err := jsonflow.EncodeAny[*ManagerLevelAsString](e, x.Level); err != nil {
			return err
		}
	}
	if !(x.Department == nil) {
		if err := e.WriteString("department"); err != nil {
			return err
		}
		if err := jsonflow.EncodeIntPtr[Department](e, x.Department); err != nil {
			return err
		}
	}
	if !(x.PrimaryContact == nil) {
		if err := e.WriteString("primaryContact"); err != nil {
			return err
		}
		if err := jsonflow.EncodeObject[*ContactInfo](e, x.PrimaryContact); err != nil {
			return err
		}
	}
	if !(len(x.Contacts) == 0) {
		if err := e.WriteString("contacts"); err != nil {
			return err
		}
		if err := jsonflow.EncodeArray(jsonflow.EncodeObject[*ContactInfo])(e, x.Contacts); err != nil {
			return err
		}
	}
	if !(len(x.Tags) == 0) {
		if err := e.WriteString("tags"); err != nil {
			return err
		}
		if err := jsonflow.EncodeMap(jsonflow.EncodeStringKey[string], jsonflow.EncodeString[string])(e, x.Tags); err != nil {
			return err
		}
	}
	if !(len(x.Labels) == 0) {
		if err := e.WriteString("labels"); err != nil {
			return err
		}
		if err := jsonflow.EncodeMap(jsonflow.EncodeStringKey[string], jsonflow.EncodeArray(jsonflow.EncodeString[string]))(e, x.Labels); err != nil {
			return err
		}
	}
	return e.WriteObjectEnd()
}

// Validate checks field values using generated validation expressions.
func (x *Manager) Validate() error {
	if x.Name != nil {
		if !(len(*x.Name) > 0 && len(*x.Name) <= 64) {
			return errutil.Explain(nil, "validate failed on \"Manager.Name\"")
		}
	}
	if x.Age != nil {
		if !(*x.Age >= MIN_AGE && *x.Age <= MAX_AGE) {
			return errutil.Explain(nil, "validate failed on \"Manager.Age\"")
		}
	}
	if x.Salary != nil {
		if !(*x.Salary >= SALARY_MIN && *x.Salary <= SALARY_MAX) {
			return errutil.Explain(nil, "validate failed on \"Manager.Salary\"")
		}
	}
	return nil
}

// Query manager by ID
type GetManagerReq struct {
	GetManagerReqBody
	Id string `json:"id" path:"id" validate:"required"`
}

// NewGetManagerReq creates a new GetManagerReq instance
// and initializes fields with default values.
func NewGetManagerReq() *GetManagerReq {
	return &GetManagerReq{}
}

// QueryForm encodes query-bound fields into URL-encoded form data.
func (x *GetManagerReq) QueryForm() (string, error) {
	return "", nil
}

// Bind extracts path and query parameters from the HTTP request
// and assigns them to the corresponding struct fields.
func (x *GetManagerReq) Bind(r *http.Request) error {
	c := httpsvr.GetRequestContext(r.Context())
	if s := c.PathValue("id"); s == "" {
		return errutil.Explain(nil, "required path parameter \"id\" is missing")
	} else {
		x.Id = s
	}
	return nil
}

// Validate validates both bound parameters and request body fields.
func (x *GetManagerReq) Validate() error {
	if err := x.GetManagerReqBody.Validate(); err != nil {
		return errutil.Explain(err, "validate failed on \"GetManagerReq\"")
	}
	return nil
}

// GetManagerReqBody represents the request body payload,
// excluding path and query parameters.
type GetManagerReqBody struct {
}

// NewGetManagerReqBody creates a new GetManagerReqBody instance
// and initializes fields with default values.
func NewGetManagerReqBody() *GetManagerReqBody {
	return &GetManagerReqBody{}
}

// EncodeForm encodes the request body as application/x-www-form-urlencoded data.
func (x *GetManagerReqBody) EncodeForm() (string, error) {
	return "", nil
}

// DecodeForm decodes application/x-www-form-urlencoded data into the request body.
func (x *GetManagerReqBody) DecodeForm(b []byte) error {
	return nil
}

// Validate checks field values using generated validation expressions.
func (x *GetManagerReqBody) Validate() error {
	return nil
}

// Create manager
type CreateManagerReq struct {
	CreateManagerReqBody
}

// NewCreateManagerReq creates a new CreateManagerReq instance
// and initializes fields with default values.
func NewCreateManagerReq() *CreateManagerReq {
	return &CreateManagerReq{}
}

// QueryForm encodes query-bound fields into URL-encoded form data.
func (x *CreateManagerReq) QueryForm() (string, error) {
	return "", nil
}

// Bind extracts path and query parameters from the HTTP request
// and assigns them to the corresponding struct fields.
func (x *CreateManagerReq) Bind(r *http.Request) error {
	return nil
}

// Validate validates both bound parameters and request body fields.
func (x *CreateManagerReq) Validate() error {
	if err := x.CreateManagerReqBody.Validate(); err != nil {
		return errutil.Explain(err, "validate failed on \"CreateManagerReq\"")
	}
	return nil
}

// CreateManagerReqBody represents the request body payload,
// excluding path and query parameters.
type CreateManagerReqBody struct {
	Name           string                `json:"name" form:"name" validate:"required"`
	Age            int64                 `json:"age" form:"age" validate:"required"`
	Vip            *bool                 `json:"vip,omitempty" form:"vip"`
	Salary         *float64              `json:"salary,omitempty" form:"salary"`
	Level          *ManagerLevelAsString `json:"level,omitempty" form:"level"`
	Department     *Department           `json:"department,omitempty" form:"department"`
	PrimaryContact *ContactInfo          `json:"primaryContact,omitempty" form:"primaryContact"`
}

// NewCreateManagerReqBody creates a new CreateManagerReqBody instance
// and initializes fields with default values.
func NewCreateManagerReqBody() *CreateManagerReqBody {
	return &CreateManagerReqBody{}
}

// DecodeJSON decodes a JSON object into CreateManagerReqBody using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *CreateManagerReqBody) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashName           = 0xc4bcadba8e631b86 // HashKey("name")
		hashAge            = 0xe715b4190539215c // HashKey("age")
		hashVip            = 0x68e906194eba76f0 // HashKey("vip")
		hashSalary         = 0x69c724098dbd2bc3 // HashKey("salary")
		hashLevel          = 0xe8ddc90a9d7c709d // HashKey("level")
		hashDepartment     = 0x9fe2b90fc81732c7 // HashKey("department")
		hashPrimaryContact = 0xb6c6aac71fb849af // HashKey("primaryContact")
	)

	var (
		hasName bool
		hasAge  bool
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashName:
			if key != "name" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			hasName = true
			if r.Name, err = jsonflow.DecodeString(d); err != nil {
				return err
			}

		case hashAge:
			if key != "age" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			hasAge = true
			if r.Age, err = jsonflow.DecodeInt[int64](d); err != nil {
				return err
			}

		case hashVip:
			if key != "vip" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Vip, err = jsonflow.DecodeBoolPtr(d); err != nil {
				return err
			}
		case hashSalary:
			if key != "salary" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Salary, err = jsonflow.DecodeFloatPtr[float64](d); err != nil {
				return err
			}
		case hashLevel:
			if key != "level" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Level, err = jsonflow.DecodeAny[*ManagerLevelAsString](d); err != nil {
				return err
			}
		case hashDepartment:
			if key != "department" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Department, err = jsonflow.DecodeIntPtr[Department](d); err != nil {
				return err
			}
		case hashPrimaryContact:
			if key != "primaryContact" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.PrimaryContact, err = jsonflow.DecodeObject(NewContactInfo)(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}

	if !hasName {
		return errutil.Explain(err, "missing required field \"name\"")
	}
	if !hasAge {
		return errutil.Explain(err, "missing required field \"age\"")
	}
	return
}

// EncodeJSON encodes CreateManagerReqBody into a JSON object using streaming
// token writes.
func (x *CreateManagerReqBody) EncodeJSON(e jsonflow.Encoder) error {
	if x == nil {
		return jsonflow.EncodeNull(e)
	}
	if err := e.WriteObjectBegin(); err != nil {
		return err
	}
	if err := e.WriteString("name"); err != nil {
		return err
	}
	if err := jsonflow.EncodeString[string](e, x.Name); err != nil {
		return err
	}
	if err := e.WriteString("age"); err != nil {
		return err
	}
	if err := jsonflow.EncodeInt[int64](e, x.Age); err != nil {
		return err
	}
	if !(x.Vip == nil) {
		if err := e.WriteString("vip"); err != nil {
			return err
		}
		if err := jsonflow.EncodeBoolPtr[bool](e, x.Vip); err != nil {
			return err
		}
	}
	if !(x.Salary == nil) {
		if err := e.WriteString("salary"); err != nil {
			return err
		}
		if err := jsonflow.EncodeFloatPtr[float64](e, x.Salary); err != nil {
			return err
		}
	}
	if !(x.Level == nil) {
		if err := e.WriteString("level"); err != nil {
			return err
		}
		if err := jsonflow.EncodeAny[*ManagerLevelAsString](e, x.Level); err != nil {
			return err
		}
	}
	if !(x.Department == nil) {
		if err := e.WriteString("department"); err != nil {
			return err
		}
		if err := jsonflow.EncodeIntPtr[Department](e, x.Department); err != nil {
			return err
		}
	}
	if !(x.PrimaryContact == nil) {
		if err := e.WriteString("primaryContact"); err != nil {
			return err
		}
		if err := jsonflow.EncodeObject[*ContactInfo](e, x.PrimaryContact); err != nil {
			return err
		}
	}
	return e.WriteObjectEnd()
}

// Validate checks field values using generated validation expressions.
func (x *CreateManagerReqBody) Validate() error {
	if !(len(x.Name) > 0 && len(x.Name) <= 64) {
		return errutil.Explain(nil, "validate failed on \"CreateManagerReq.Name\"")
	}
	if !(x.Age >= MIN_AGE && x.Age <= MAX_AGE) {
		return errutil.Explain(nil, "validate failed on \"CreateManagerReq.Age\"")
	}
	if x.Salary != nil {
		if !(*x.Salary >= SALARY_MIN && *x.Salary <= SALARY_MAX) {
			return errutil.Explain(nil, "validate failed on \"CreateManagerReq.Salary\"")
		}
	}
	if x.PrimaryContact != nil {
		if err := x.PrimaryContact.Validate(); err != nil {
			return errutil.Explain(err, "validate failed on \"CreateManagerReq.PrimaryContact\"")
		}
	}
	return nil
}

// Update manager
type UpdateManagerReq struct {
	UpdateManagerReqBody
	Id string `json:"id" path:"id" validate:"required"`
}

// NewUpdateManagerReq creates a new UpdateManagerReq instance
// and initializes fields with default values.
func NewUpdateManagerReq() *UpdateManagerReq {
	return &UpdateManagerReq{}
}

// QueryForm encodes query-bound fields into URL-encoded form data.
func (x *UpdateManagerReq) QueryForm() (string, error) {
	return "", nil
}

// Bind extracts path and query parameters from the HTTP request
// and assigns them to the corresponding struct fields.
func (x *UpdateManagerReq) Bind(r *http.Request) error {
	c := httpsvr.GetRequestContext(r.Context())
	if s := c.PathValue("id"); s == "" {
		return errutil.Explain(nil, "required path parameter \"id\" is missing")
	} else {
		x.Id = s
	}
	return nil
}

// Validate validates both bound parameters and request body fields.
func (x *UpdateManagerReq) Validate() error {
	if err := x.UpdateManagerReqBody.Validate(); err != nil {
		return errutil.Explain(err, "validate failed on \"UpdateManagerReq\"")
	}
	return nil
}

// UpdateManagerReqBody represents the request body payload,
// excluding path and query parameters.
type UpdateManagerReqBody struct {
	Name           *string       `json:"name,omitempty" form:"name"`
	Age            *int64        `json:"age,omitempty" form:"age"`
	Vip            *bool         `json:"vip" form:"vip"`
	Salary         *float64      `json:"salary,omitempty" form:"salary"`
	Level          *ManagerLevel `json:"level,omitempty" form:"level"`
	Department     *Department   `json:"department,omitempty" form:"department"`
	PrimaryContact *ContactInfo  `json:"primaryContact,omitempty" form:"primaryContact"`
}

// NewUpdateManagerReqBody creates a new UpdateManagerReqBody instance
// and initializes fields with default values.
func NewUpdateManagerReqBody() *UpdateManagerReqBody {
	return &UpdateManagerReqBody{}
}

// DecodeJSON decodes a JSON object into UpdateManagerReqBody using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *UpdateManagerReqBody) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashName           = 0xc4bcadba8e631b86 // HashKey("name")
		hashAge            = 0xe715b4190539215c // HashKey("age")
		hashVip            = 0x68e906194eba76f0 // HashKey("vip")
		hashSalary         = 0x69c724098dbd2bc3 // HashKey("salary")
		hashLevel          = 0xe8ddc90a9d7c709d // HashKey("level")
		hashDepartment     = 0x9fe2b90fc81732c7 // HashKey("department")
		hashPrimaryContact = 0xb6c6aac71fb849af // HashKey("primaryContact")
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashName:
			if key != "name" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Name, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashAge:
			if key != "age" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Age, err = jsonflow.DecodeIntPtr[int64](d); err != nil {
				return err
			}
		case hashVip:
			if key != "vip" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Vip, err = jsonflow.DecodeBoolPtr(d); err != nil {
				return err
			}
		case hashSalary:
			if key != "salary" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Salary, err = jsonflow.DecodeFloatPtr[float64](d); err != nil {
				return err
			}
		case hashLevel:
			if key != "level" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Level, err = jsonflow.DecodeIntPtr[ManagerLevel](d); err != nil {
				return err
			}
		case hashDepartment:
			if key != "department" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Department, err = jsonflow.DecodeIntPtr[Department](d); err != nil {
				return err
			}
		case hashPrimaryContact:
			if key != "primaryContact" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.PrimaryContact, err = jsonflow.DecodeObject(NewContactInfo)(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}
	return
}

// EncodeJSON encodes UpdateManagerReqBody into a JSON object using streaming
// token writes.
func (x *UpdateManagerReqBody) EncodeJSON(e jsonflow.Encoder) error {
	if x == nil {
		return jsonflow.EncodeNull(e)
	}
	if err := e.WriteObjectBegin(); err != nil {
		return err
	}
	if !(x.Name == nil) {
		if err := e.WriteString("name"); err != nil {
			return err
		}
		if err := jsonflow.EncodeStringPtr[string](e, x.Name); err != nil {
			return err
		}
	}
	if !(x.Age == nil) {
		if err := e.WriteString("age"); err != nil {
			return err
		}
		if err := jsonflow.EncodeIntPtr[int64](e, x.Age); err != nil {
			return err
		}
	}
	if err := e.WriteString("vip"); err != nil {
		return err
	}
	if err := jsonflow.EncodeBoolPtr[bool](e, x.Vip); err != nil {
		return err
	}
	if !(x.Salary == nil) {
		if err := e.WriteString("salary"); err != nil {
			return err
		}
		if err := jsonflow.EncodeFloatPtr[float64](e, x.Salary); err != nil {
			return err
		}
	}
	if !(x.Level == nil) {
		if err := e.WriteString("level"); err != nil {
			return err
		}
		if err := jsonflow.EncodeIntPtr[ManagerLevel](e, x.Level); err != nil {
			return err
		}
	}
	if !(x.Department == nil) {
		if err := e.WriteString("department"); err != nil {
			return err
		}
		if err := jsonflow.EncodeIntPtr[Department](e, x.Department); err != nil {
			return err
		}
	}
	if !(x.PrimaryContact == nil) {
		if err := e.WriteString("primaryContact"); err != nil {
			return err
		}
		if err := jsonflow.EncodeObject[*ContactInfo](e, x.PrimaryContact); err != nil {
			return err
		}
	}
	return e.WriteObjectEnd()
}

// Validate checks field values using generated validation expressions.
func (x *UpdateManagerReqBody) Validate() error {
	if x.Age != nil {
		if !(*x.Age >= MIN_AGE && *x.Age <= MAX_AGE) {
			return errutil.Explain(nil, "validate failed on \"UpdateManagerReq.Age\"")
		}
	}
	if x.Salary != nil {
		if !(*x.Salary >= SALARY_MIN && *x.Salary <= SALARY_MAX) {
			return errutil.Explain(nil, "validate failed on \"UpdateManagerReq.Salary\"")
		}
	}
	if x.PrimaryContact != nil {
		if err := x.PrimaryContact.Validate(); err != nil {
			return errutil.Explain(err, "validate failed on \"UpdateManagerReq.PrimaryContact\"")
		}
	}
	return nil
}

// List managers with filters
type ListManagersReq struct {
	ListManagersReqBody
	Page       int64         `json:"page" query:"page" validate:"required"`
	Size       int64         `json:"size" query:"size" validate:"required"`
	Keyword    []string      `json:"keyword,omitempty" query:"keyword"`
	Department *Department   `json:"department,omitempty" query:"department"`
	MinLevel   *ManagerLevel `json:"minLevel,omitempty" query:"minLevel"`
	Vip        *bool         `json:"vip,omitempty" query:"vip"`
}

// NewListManagersReq creates a new ListManagersReq instance
// and initializes fields with default values.
func NewListManagersReq() *ListManagersReq {
	return &ListManagersReq{}
}

// QueryForm encodes query-bound fields into URL-encoded form data.
func (x *ListManagersReq) QueryForm() (string, error) {
	form := make(url.Values)
	if err := formutil.EncodeInt(form, "page", x.Page); err != nil {
		return "", errutil.Explain(err, "encode form field \"page\" error")
	}
	if err := formutil.EncodeInt(form, "size", x.Size); err != nil {
		return "", errutil.Explain(err, "encode form field \"size\" error")
	}
	if err := formutil.EncodeList(form, "keyword", x.Keyword, formutil.EncodeString); err != nil {
		return "", errutil.Explain(err, "encode form field \"keyword\" error")
	}
	if err := formutil.EncodeIntPtr(form, "department", x.Department); err != nil {
		return "", errutil.Explain(err, "encode form field \"department\" error")
	}
	if err := formutil.EncodeIntPtr(form, "minLevel", x.MinLevel); err != nil {
		return "", errutil.Explain(err, "encode form field \"minLevel\" error")
	}
	if err := formutil.EncodeBoolPtr(form, "vip", x.Vip); err != nil {
		return "", errutil.Explain(err, "encode form field \"vip\" error")
	}
	return form.Encode(), nil
}

// Bind extracts path and query parameters from the HTTP request
// and assigns them to the corresponding struct fields.
func (x *ListManagersReq) Bind(r *http.Request) error {
	form, err := url.ParseQuery(r.URL.RawQuery)
	if err != nil {
		return errutil.Explain(err, "parse query error")
	}

	var (
		hasPage bool
		hasSize bool
	)

	for key, values := range form {
		if len(values) == 0 {
			continue
		}
		switch key {
		case "page":
			hasPage = true
			if x.Page, err = formutil.DecodeInt[int64](key, values); err != nil {
				return errutil.Explain(err, "decode form field \"page\" error")
			}
		case "size":
			hasSize = true
			if x.Size, err = formutil.DecodeInt[int64](key, values); err != nil {
				return errutil.Explain(err, "decode form field \"size\" error")
			}
		case "keyword":
			if x.Keyword, err = formutil.DecodeList(key, values, formutil.DecodeString); err != nil {
				return errutil.Explain(err, "decode form field \"keyword\" error")
			}
		case "department":
			if x.Department, err = formutil.DecodeIntPtr[Department](key, values); err != nil {
				return errutil.Explain(err, "decode form field \"department\" error")
			}
		case "minLevel":
			if x.MinLevel, err = formutil.DecodeIntPtr[ManagerLevel](key, values); err != nil {
				return errutil.Explain(err, "decode form field \"minLevel\" error")
			}
		case "vip":
			if x.Vip, err = formutil.DecodeBoolPtr(key, values); err != nil {
				return errutil.Explain(err, "decode form field \"vip\" error")
			}
		}
	}

	if !hasPage {
		err = errutil.Explain(err, "missing required field \"page\"")
	}
	if !hasSize {
		err = errutil.Explain(err, "missing required field \"size\"")
	}
	return nil
}

// Validate validates both bound parameters and request body fields.
func (x *ListManagersReq) Validate() error {
	if !(x.Page >= 1) {
		return errutil.Explain(nil, "validate failed on \"ListManagersReq.Page\"")
	}
	if !(x.Size >= 1 && x.Size <= MAX_PAGE_SIZE) {
		return errutil.Explain(nil, "validate failed on \"ListManagersReq.Size\"")
	}
	if !(len(x.Keyword) <= 5) {
		return errutil.Explain(nil, "validate failed on \"ListManagersReq.Keyword\"")
	}
	if err := x.ListManagersReqBody.Validate(); err != nil {
		return errutil.Explain(err, "validate failed on \"ListManagersReq\"")
	}
	return nil
}

// ListManagersReqBody represents the request body payload,
// excluding path and query parameters.
type ListManagersReqBody struct {
}

// NewListManagersReqBody creates a new ListManagersReqBody instance
// and initializes fields with default values.
func NewListManagersReqBody() *ListManagersReqBody {
	return &ListManagersReqBody{}
}

// EncodeForm encodes the request body as application/x-www-form-urlencoded data.
func (x *ListManagersReqBody) EncodeForm() (string, error) {
	return "", nil
}

// DecodeForm decodes application/x-www-form-urlencoded data into the request body.
func (x *ListManagersReqBody) DecodeForm(b []byte) error {
	return nil
}

// Validate checks field values using generated validation expressions.
func (x *ListManagersReqBody) Validate() error {
	return nil
}

type GetManagerResp struct {
	Code      ErrCode  `json:"code" form:"code" validate:"required"`
	Message   string   `json:"message" form:"message" validate:"required"`
	RequestId *string  `json:"requestId,omitempty" form:"requestId"`
	Data      *Manager `json:"data,omitempty" form:"data"`
}

// NewGetManagerResp creates a new GetManagerResp instance
// and initializes fields with default values.
func NewGetManagerResp() *GetManagerResp {
	return &GetManagerResp{}
}

// DecodeJSON decodes a JSON object into GetManagerResp using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *GetManagerResp) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashCode      = 0xbb51791194b4414  // HashKey("code")
		hashMessage   = 0x546401b5d2a8d2a4 // HashKey("message")
		hashRequestId = 0xd9518651bf9ee11f // HashKey("requestId")
		hashData      = 0x855b556730a34a05 // HashKey("data")
	)

	var (
		hasCode    bool
		hasMessage bool
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashCode:
			if key != "code" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			hasCode = true
			if r.Code, err = jsonflow.DecodeInt[ErrCode](d); err != nil {
				return err
			}

		case hashMessage:
			if key != "message" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			hasMessage = true
			if r.Message, err = jsonflow.DecodeString(d); err != nil {
				return err
			}

		case hashRequestId:
			if key != "requestId" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.RequestId, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashData:
			if key != "data" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Data, err = jsonflow.DecodeObject(NewManager)(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}

	if !hasCode {
		return errutil.Explain(err, "missing required field \"code\"")
	}
	if !hasMessage {
		return errutil.Explain(err, "missing required field \"message\"")
	}
	return
}

// EncodeJSON encodes GetManagerResp into a JSON object using streaming
// token writes.
func (x *GetManagerResp) EncodeJSON(e jsonflow.Encoder) error {
	if x == nil {
		return jsonflow.EncodeNull(e)
	}
	if err := e.WriteObjectBegin(); err != nil {
		return err
	}
	if err := e.WriteString("code"); err != nil {
		return err
	}
	if err := jsonflow.EncodeInt[ErrCode](e, x.Code); err != nil {
		return err
	}
	if err := e.WriteString("message"); err != nil {
		return err
	}
	if err := jsonflow.EncodeString[string](e, x.Message); err != nil {
		return err
	}
	if !(x.RequestId == nil) {
		if err := e.WriteString("requestId"); err != nil {
			return err
		}
		if err := jsonflow.EncodeStringPtr[string](e, x.RequestId); err != nil {
			return err
		}
	}
	if !(x.Data == nil) {
		if err := e.WriteString("data"); err != nil {
			return err
		}
		if err := jsonflow.EncodeObject[*Manager](e, x.Data); err != nil {
			return err
		}
	}
	return e.WriteObjectEnd()
}

type CreateManagerResp struct {
	Code      ErrCode  `json:"code" form:"code" validate:"required"`
	Message   string   `json:"message" form:"message" validate:"required"`
	RequestId *string  `json:"requestId,omitempty" form:"requestId"`
	Data      *Manager `json:"data,omitempty" form:"data"`
}

// NewCreateManagerResp creates a new CreateManagerResp instance
// and initializes fields with default values.
func NewCreateManagerResp() *CreateManagerResp {
	return &CreateManagerResp{}
}

// DecodeJSON decodes a JSON object into CreateManagerResp using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *CreateManagerResp) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashCode      = 0xbb51791194b4414  // HashKey("code")
		hashMessage   = 0x546401b5d2a8d2a4 // HashKey("message")
		hashRequestId = 0xd9518651bf9ee11f // HashKey("requestId")
		hashData      = 0x855b556730a34a05 // HashKey("data")
	)

	var (
		hasCode    bool
		hasMessage bool
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashCode:
			if key != "code" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			hasCode = true
			if r.Code, err = jsonflow.DecodeInt[ErrCode](d); err != nil {
				return err
			}

		case hashMessage:
			if key != "message" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			hasMessage = true
			if r.Message, err = jsonflow.DecodeString(d); err != nil {
				return err
			}

		case hashRequestId:
			if key != "requestId" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.RequestId, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashData:
			if key != "data" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Data, err = jsonflow.DecodeObject(NewManager)(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}

	if !hasCode {
		return errutil.Explain(err, "missing required field \"code\"")
	}
	if !hasMessage {
		return errutil.Explain(err, "missing required field \"message\"")
	}
	return
}

// EncodeJSON encodes CreateManagerResp into a JSON object using streaming
// token writes.
func (x *CreateManagerResp) EncodeJSON(e jsonflow.Encoder) error {
	if x == nil {
		return jsonflow.EncodeNull(e)
	}
	if err := e.WriteObjectBegin(); err != nil {
		return err
	}
	if err := e.WriteString("code"); err != nil {
		return err
	}
	if err := jsonflow.EncodeInt[ErrCode](e, x.Code); err != nil {
		return err
	}
	if err := e.WriteString("message"); err != nil {
		return err
	}
	if err := jsonflow.EncodeString[string](e, x.Message); err != nil {
		return err
	}
	if !(x.RequestId == nil) {
		if err := e.WriteString("requestId"); err != nil {
			return err
		}
		if err := jsonflow.EncodeStringPtr[string](e, x.RequestId); err != nil {
			return err
		}
	}
	if !(x.Data == nil) {
		if err := e.WriteString("data"); err != nil {
			return err
		}
		if err := jsonflow.EncodeObject[*Manager](e, x.Data); err != nil {
			return err
		}
	}
	return e.WriteObjectEnd()
}

type UpdateManagerResp struct {
	Code      ErrCode  `json:"code" form:"code" validate:"required"`
	Message   string   `json:"message" form:"message" validate:"required"`
	RequestId *string  `json:"requestId,omitempty" form:"requestId"`
	Data      *Manager `json:"data,omitempty" form:"data"`
}

// NewUpdateManagerResp creates a new UpdateManagerResp instance
// and initializes fields with default values.
func NewUpdateManagerResp() *UpdateManagerResp {
	return &UpdateManagerResp{}
}

// DecodeJSON decodes a JSON object into UpdateManagerResp using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *UpdateManagerResp) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashCode      = 0xbb51791194b4414  // HashKey("code")
		hashMessage   = 0x546401b5d2a8d2a4 // HashKey("message")
		hashRequestId = 0xd9518651bf9ee11f // HashKey("requestId")
		hashData      = 0x855b556730a34a05 // HashKey("data")
	)

	var (
		hasCode    bool
		hasMessage bool
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashCode:
			if key != "code" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			hasCode = true
			if r.Code, err = jsonflow.DecodeInt[ErrCode](d); err != nil {
				return err
			}

		case hashMessage:
			if key != "message" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			hasMessage = true
			if r.Message, err = jsonflow.DecodeString(d); err != nil {
				return err
			}

		case hashRequestId:
			if key != "requestId" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.RequestId, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashData:
			if key != "data" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Data, err = jsonflow.DecodeObject(NewManager)(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}

	if !hasCode {
		return errutil.Explain(err, "missing required field \"code\"")
	}
	if !hasMessage {
		return errutil.Explain(err, "missing required field \"message\"")
	}
	return
}

// EncodeJSON encodes UpdateManagerResp into a JSON object using streaming
// token writes.
func (x *UpdateManagerResp) EncodeJSON(e jsonflow.Encoder) error {
	if x == nil {
		return jsonflow.EncodeNull(e)
	}
	if err := e.WriteObjectBegin(); err != nil {
		return err
	}
	if err := e.WriteString("code"); err != nil {
		return err
	}
	if err := jsonflow.EncodeInt[ErrCode](e, x.Code); err != nil {
		return err
	}
	if err := e.WriteString("message"); err != nil {
		return err
	}
	if err := jsonflow.EncodeString[string](e, x.Message); err != nil {
		return err
	}
	if !(x.RequestId == nil) {
		if err := e.WriteString("requestId"); err != nil {
			return err
		}
		if err := jsonflow.EncodeStringPtr[string](e, x.RequestId); err != nil {
			return err
		}
	}
	if !(x.Data == nil) {
		if err := e.WriteString("data"); err != nil {
			return err
		}
		if err := jsonflow.EncodeObject[*Manager](e, x.Data); err != nil {
			return err
		}
	}
	return e.WriteObjectEnd()
}

type DeleteManagerResp struct {
	Code      ErrCode `json:"code" form:"code" validate:"required"`
	Message   string  `json:"message" form:"message" validate:"required"`
	RequestId *string `json:"requestId,omitempty" form:"requestId"`
	Data      *bool   `json:"data,omitempty" form:"data"`
}

// NewDeleteManagerResp creates a new DeleteManagerResp instance
// and initializes fields with default values.
func NewDeleteManagerResp() *DeleteManagerResp {
	return &DeleteManagerResp{}
}

// DecodeJSON decodes a JSON object into DeleteManagerResp using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *DeleteManagerResp) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashCode      = 0xbb51791194b4414  // HashKey("code")
		hashMessage   = 0x546401b5d2a8d2a4 // HashKey("message")
		hashRequestId = 0xd9518651bf9ee11f // HashKey("requestId")
		hashData      = 0x855b556730a34a05 // HashKey("data")
	)

	var (
		hasCode    bool
		hasMessage bool
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashCode:
			if key != "code" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			hasCode = true
			if r.Code, err = jsonflow.DecodeInt[ErrCode](d); err != nil {
				return err
			}

		case hashMessage:
			if key != "message" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			hasMessage = true
			if r.Message, err = jsonflow.DecodeString(d); err != nil {
				return err
			}

		case hashRequestId:
			if key != "requestId" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.RequestId, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashData:
			if key != "data" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Data, err = jsonflow.DecodeBoolPtr(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}

	if !hasCode {
		return errutil.Explain(err, "missing required field \"code\"")
	}
	if !hasMessage {
		return errutil.Explain(err, "missing required field \"message\"")
	}
	return
}

// EncodeJSON encodes DeleteManagerResp into a JSON object using streaming
// token writes.
func (x *DeleteManagerResp) EncodeJSON(e jsonflow.Encoder) error {
	if x == nil {
		return jsonflow.EncodeNull(e)
	}
	if err := e.WriteObjectBegin(); err != nil {
		return err
	}
	if err := e.WriteString("code"); err != nil {
		return err
	}
	if err := jsonflow.EncodeInt[ErrCode](e, x.Code); err != nil {
		return err
	}
	if err := e.WriteString("message"); err != nil {
		return err
	}
	if err := jsonflow.EncodeString[string](e, x.Message); err != nil {
		return err
	}
	if !(x.RequestId == nil) {
		if err := e.WriteString("requestId"); err != nil {
			return err
		}
		if err := jsonflow.EncodeStringPtr[string](e, x.RequestId); err != nil {
			return err
		}
	}
	if !(x.Data == nil) {
		if err := e.WriteString("data"); err != nil {
			return err
		}
		if err := jsonflow.EncodeBoolPtr[bool](e, x.Data); err != nil {
			return err
		}
	}
	return e.WriteObjectEnd()
}

type ManagersPageData struct {
	Total *int64     `json:"total,omitempty" form:"total"`
	Page  *int64     `json:"page,omitempty" form:"page"`
	Size  *int64     `json:"size,omitempty" form:"size"`
	Items []*Manager `json:"items,omitempty" form:"items"`
}

// NewManagersPageData creates a new ManagersPageData instance
// and initializes fields with default values.
func NewManagersPageData() *ManagersPageData {
	return &ManagersPageData{}
}

// DecodeJSON decodes a JSON object into ManagersPageData using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *ManagersPageData) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashTotal = 0x2dcede7d543a4ffd // HashKey("total")
		hashPage  = 0x38b2a0deba58916  // HashKey("page")
		hashSize  = 0x4dea9618e618ae3c // HashKey("size")
		hashItems = 0x3e7884bf4f412c6f // HashKey("items")
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashTotal:
			if key != "total" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Total, err = jsonflow.DecodeIntPtr[int64](d); err != nil {
				return err
			}
		case hashPage:
			if key != "page" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Page, err = jsonflow.DecodeIntPtr[int64](d); err != nil {
				return err
			}
		case hashSize:
			if key != "size" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Size, err = jsonflow.DecodeIntPtr[int64](d); err != nil {
				return err
			}
		case hashItems:
			if key != "items" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Items, err = jsonflow.DecodeArray(jsonflow.DecodeObject(NewManager))(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}
	return
}

// EncodeJSON encodes ManagersPageData into a JSON object using streaming
// token writes.
func (x *ManagersPageData) EncodeJSON(e jsonflow.Encoder) error {
	if x == nil {
		return jsonflow.EncodeNull(e)
	}
	if err := e.WriteObjectBegin(); err != nil {
		return err
	}
	if !(x.Total == nil) {
		if err := e.WriteString("total"); err != nil {
			return err
		}
		if err := jsonflow.EncodeIntPtr[int64](e, x.Total); err != nil {
			return err
		}
	}
	if !(x.Page == nil) {
		if err := e.WriteString("page"); err != nil {
			return err
		}
		if err := jsonflow.EncodeIntPtr[int64](e, x.Page); err != nil {
			return err
		}
	}
	if !(x.Size == nil) {
		if err := e.WriteString("size"); err != nil {
			return err
		}
		if err := jsonflow.EncodeIntPtr[int64](e, x.Size); err != nil {
			return err
		}
	}
	if !(len(x.Items) == 0) {
		if err := e.WriteString("items"); err != nil {
			return err
		}
		if err := jsonflow.EncodeArray(jsonflow.EncodeObject[*Manager])(e, x.Items); err != nil {
			return err
		}
	}
	return e.WriteObjectEnd()
}

type ListManagersResp struct {
	Code      ErrCode           `json:"code" form:"code" validate:"required"`
	Message   string            `json:"message" form:"message" validate:"required"`
	RequestId *string           `json:"requestId,omitempty" form:"requestId"`
	Data      *ManagersPageData `json:"data,omitempty" form:"data"`
}

// NewListManagersResp creates a new ListManagersResp instance
// and initializes fields with default values.
func NewListManagersResp() *ListManagersResp {
	return &ListManagersResp{}
}

// DecodeJSON decodes a JSON object into ListManagersResp using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *ListManagersResp) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashCode      = 0xbb51791194b4414  // HashKey("code")
		hashMessage   = 0x546401b5d2a8d2a4 // HashKey("message")
		hashRequestId = 0xd9518651bf9ee11f // HashKey("requestId")
		hashData      = 0x855b556730a34a05 // HashKey("data")
	)

	var (
		hasCode    bool
		hasMessage bool
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashCode:
			if key != "code" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			hasCode = true
			if r.Code, err = jsonflow.DecodeInt[ErrCode](d); err != nil {
				return err
			}

		case hashMessage:
			if key != "message" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			hasMessage = true
			if r.Message, err = jsonflow.DecodeString(d); err != nil {
				return err
			}

		case hashRequestId:
			if key != "requestId" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.RequestId, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashData:
			if key != "data" {
				if err = d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if r.Data, err = jsonflow.DecodeObject(NewManagersPageData)(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}

	if !hasCode {
		return errutil.Explain(err, "missing required field \"code\"")
	}
	if !hasMessage {
		return errutil.Explain(err, "missing required field \"message\"")
	}
	return
}

// EncodeJSON encodes ListManagersResp into a JSON object using streaming
// token writes.
func (x *ListManagersResp) EncodeJSON(e jsonflow.Encoder) error {
	if x == nil {
		return jsonflow.EncodeNull(e)
	}
	if err := e.WriteObjectBegin(); err != nil {
		return err
	}
	if err := e.WriteString("code"); err != nil {
		return err
	}
	if err := jsonflow.EncodeInt[ErrCode](e, x.Code); err != nil {
		return err
	}
	if err := e.WriteString("message"); err != nil {
		return err
	}
	if err := jsonflow.EncodeString[string](e, x.Message); err != nil {
		return err
	}
	if !(x.RequestId == nil) {
		if err := e.WriteString("requestId"); err != nil {
			return err
		}
		if err := jsonflow.EncodeStringPtr[string](e, x.RequestId); err != nil {
			return err
		}
	}
	if !(x.Data == nil) {
		if err := e.WriteString("data"); err != nil {
			return err
		}
		if err := jsonflow.EncodeObject[*ManagersPageData](e, x.Data); err != nil {
			return err
		}
	}
	return e.WriteObjectEnd()
}
