// Code generated by gs-http-gen compiler. DO NOT EDIT.

package proto

import (
	"context"
	"net/http"

	"github.com/go-spring/stdlib/httpsvr"
)

// ManagerService defines the interface that service must implement.
type ManagerService interface {
	// Streaming assistant interface
	Assistant(context.Context, *AssistantReq, chan<- *httpsvr.Event[*AssistantEvent])
	// Create a new manager
	CreateManager(context.Context, *CreateManagerReq) *CreateManagerResp
	// Delete manager
	DeleteManager(context.Context, *GetManagerReq) *DeleteManagerResp
	// Get manager by ID
	GetManager(context.Context, *GetManagerReq) *GetManagerResp
	// List managers with pagination
	ListManagers(context.Context, *ListManagersReq) *ListManagersResp
	// Update manager
	UpdateManager(context.Context, *UpdateManagerReq) *UpdateManagerResp
}

// Routers returns a list of HTTP routers for the service.
func Routers(server ManagerService, fn httpsvr.NewRequestContext) []httpsvr.Router {
	return []httpsvr.Router{
		{
			Method:  "POST",
			Pattern: "/assistant/stream",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				ctx := httpsvr.WithRequestContext(r.Context(), fn(r, w))
				httpsvr.HandleStream(w, r.WithContext(ctx), NewAssistantReq(), server.Assistant)
			},
		},
		{
			Method:  "DELETE",
			Pattern: "/managers/{id}",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				ctx := httpsvr.WithRequestContext(r.Context(), fn(r, w))
				httpsvr.HandleJSON(w, r.WithContext(ctx), NewGetManagerReq(), server.DeleteManager)
			},
		},
		{
			Method:  "GET",
			Pattern: "/managers/{id}",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				ctx := httpsvr.WithRequestContext(r.Context(), fn(r, w))
				httpsvr.HandleJSON(w, r.WithContext(ctx), NewGetManagerReq(), server.GetManager)
			},
		},
		{
			Method:  "PUT",
			Pattern: "/managers/{id}",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				ctx := httpsvr.WithRequestContext(r.Context(), fn(r, w))
				httpsvr.HandleJSON(w, r.WithContext(ctx), NewUpdateManagerReq(), server.UpdateManager)
			},
		},
		{
			Method:  "POST",
			Pattern: "/managers",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				ctx := httpsvr.WithRequestContext(r.Context(), fn(r, w))
				httpsvr.HandleJSON(w, r.WithContext(ctx), NewCreateManagerReq(), server.CreateManager)
			},
		},
		{
			Method:  "GET",
			Pattern: "/managers",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				ctx := httpsvr.WithRequestContext(r.Context(), fn(r, w))
				httpsvr.HandleJSON(w, r.WithContext(ctx), NewListManagersReq(), server.ListManagers)
			},
		},
	}
}
