// Code generated by gs-http-gen compiler. DO NOT EDIT.

package proto

// Email is a default validation function for fields of type string.
// This serves as a placeholder that can be overridden or extended.
var Email = func(string) bool { return true }
