services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.17
    container_name: starter-etcd-config
    command:
      - etcd
      - --name=etcd0
      - --data-dir=/etcd-data
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
    ports:
      - "127.0.0.1:2379:2379"
