// Code generated by Kitex v0.16.3. DO NOT EDIT.

package gs_project_nameservice

import (
	"context"
	"errors"

	svc "GS_PROJECT_MODULE/idl/kitex/kitex_gen/svc"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

// methodInfo captures the wiring for one thrift method: how to allocate the
// Args/Result envelopes, and how to invoke the handler with them. In a real
// Kitex build this would be `kitex.MethodInfo`; the template stays dep-free.
type methodInfo struct {
	handler       func(ctx context.Context, handler interface{}, arg, result interface{}) error
	newArgsFunc   func() interface{}
	newResultFunc func() interface{}
	oneway        bool
}

// serviceMethods is the method registry consumed by NewServiceInfo. Each entry
// mirrors the shape thriftgo/kitex emits.
//
// TODO: in a real kitex build these entries would be kitex.NewMethodInfo(...)
// values with kitex.WithStreamingMode(kitex.StreamingNone).
var serviceMethods = map[string]methodInfo{
	"Ping": {
		handler:       pingHandler,
		newArgsFunc:   newGS_PROJECT_NAMEServicePingArgs,
		newResultFunc: newGS_PROJECT_NAMEServicePingResult,
	},
	"CreateOrder": {
		handler:       createOrderHandler,
		newArgsFunc:   newGS_PROJECT_NAMEServiceCreateOrderArgs,
		newResultFunc: newGS_PROJECT_NAMEServiceCreateOrderResult,
	},
	"PayOrder": {
		handler:       payOrderHandler,
		newArgsFunc:   newGS_PROJECT_NAMEServicePayOrderArgs,
		newResultFunc: newGS_PROJECT_NAMEServicePayOrderResult,
	},
	"ShipOrder": {
		handler:       shipOrderHandler,
		newArgsFunc:   newGS_PROJECT_NAMEServiceShipOrderArgs,
		newResultFunc: newGS_PROJECT_NAMEServiceShipOrderResult,
	},
	"RegisterUser": {
		handler:       registerUserHandler,
		newArgsFunc:   newGS_PROJECT_NAMEServiceRegisterUserArgs,
		newResultFunc: newGS_PROJECT_NAMEServiceRegisterUserResult,
	},
	"UpgradeUser": {
		handler:       upgradeUserHandler,
		newArgsFunc:   newGS_PROJECT_NAMEServiceUpgradeUserArgs,
		newResultFunc: newGS_PROJECT_NAMEServiceUpgradeUserResult,
	},
}

// ServiceInfo is a stand-in for kitex.ServiceInfo. The real generated file
// returns *kitex.ServiceInfo built from serviceMethods; the template keeps
// the shape so the wiring is obvious.
type ServiceInfo struct {
	ServiceName     string
	HandlerType     interface{}
	Methods         map[string]methodInfo
	KiteXGenVersion string
	Extra           map[string]interface{}
}

// NewServiceInfo creates the ServiceInfo used to register the service with a
// Kitex server. Callers pass this alongside the handler bean to server.NewServer.
//
// TODO: in a real kitex build return *kitex.ServiceInfo{ ServiceName: "GS_PROJECT_NAMEService",
// HandlerType: (*svc.GS_PROJECT_NAMEService)(nil), Methods: ..., PayloadCodec: kitex.Thrift, ... }.
func NewServiceInfo() *ServiceInfo {
	return &ServiceInfo{
		ServiceName:     "GS_PROJECT_NAMEService",
		HandlerType:     (*svc.GS_PROJECT_NAMEService)(nil),
		Methods:         serviceMethods,
		KiteXGenVersion: "v0.16.3",
		Extra:           map[string]interface{}{"PackageName": "svc"},
	}
}

// --- Per-method handler adapters. Each unwraps the Args, invokes the user
// handler on the svc.GS_PROJECT_NAMEService interface, then stuffs the return
// value into the Result envelope. Shape mirrors thriftgo/kitex output. ---

func pingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg, ok := arg.(*svc.GS_PROJECT_NAMEServicePingArgs)
	if !ok {
		return errInvalidMessageType
	}
	realResult, ok := result.(*svc.GS_PROJECT_NAMEServicePingResult)
	if !ok {
		return errInvalidMessageType
	}
	success, err := handler.(svc.GS_PROJECT_NAMEService).Ping(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func createOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg, ok := arg.(*svc.GS_PROJECT_NAMEServiceCreateOrderArgs)
	if !ok {
		return errInvalidMessageType
	}
	realResult, ok := result.(*svc.GS_PROJECT_NAMEServiceCreateOrderResult)
	if !ok {
		return errInvalidMessageType
	}
	success, err := handler.(svc.GS_PROJECT_NAMEService).CreateOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func payOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg, ok := arg.(*svc.GS_PROJECT_NAMEServicePayOrderArgs)
	if !ok {
		return errInvalidMessageType
	}
	realResult, ok := result.(*svc.GS_PROJECT_NAMEServicePayOrderResult)
	if !ok {
		return errInvalidMessageType
	}
	success, err := handler.(svc.GS_PROJECT_NAMEService).PayOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func shipOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg, ok := arg.(*svc.GS_PROJECT_NAMEServiceShipOrderArgs)
	if !ok {
		return errInvalidMessageType
	}
	realResult, ok := result.(*svc.GS_PROJECT_NAMEServiceShipOrderResult)
	if !ok {
		return errInvalidMessageType
	}
	success, err := handler.(svc.GS_PROJECT_NAMEService).ShipOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func registerUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg, ok := arg.(*svc.GS_PROJECT_NAMEServiceRegisterUserArgs)
	if !ok {
		return errInvalidMessageType
	}
	realResult, ok := result.(*svc.GS_PROJECT_NAMEServiceRegisterUserResult)
	if !ok {
		return errInvalidMessageType
	}
	success, err := handler.(svc.GS_PROJECT_NAMEService).RegisterUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func upgradeUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg, ok := arg.(*svc.GS_PROJECT_NAMEServiceUpgradeUserArgs)
	if !ok {
		return errInvalidMessageType
	}
	realResult, ok := result.(*svc.GS_PROJECT_NAMEServiceUpgradeUserResult)
	if !ok {
		return errInvalidMessageType
	}
	success, err := handler.(svc.GS_PROJECT_NAMEService).UpgradeUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

// --- Args/Result constructors. In real kitex output these are the newXxx
// closures passed to kitex.NewMethodInfo. ---

func newGS_PROJECT_NAMEServicePingArgs() interface{} {
	return svc.NewGS_PROJECT_NAMEServicePingArgs()
}
func newGS_PROJECT_NAMEServicePingResult() interface{} {
	return svc.NewGS_PROJECT_NAMEServicePingResult()
}

func newGS_PROJECT_NAMEServiceCreateOrderArgs() interface{} {
	return svc.NewGS_PROJECT_NAMEServiceCreateOrderArgs()
}
func newGS_PROJECT_NAMEServiceCreateOrderResult() interface{} {
	return svc.NewGS_PROJECT_NAMEServiceCreateOrderResult()
}

func newGS_PROJECT_NAMEServicePayOrderArgs() interface{} {
	return svc.NewGS_PROJECT_NAMEServicePayOrderArgs()
}
func newGS_PROJECT_NAMEServicePayOrderResult() interface{} {
	return svc.NewGS_PROJECT_NAMEServicePayOrderResult()
}

func newGS_PROJECT_NAMEServiceShipOrderArgs() interface{} {
	return svc.NewGS_PROJECT_NAMEServiceShipOrderArgs()
}
func newGS_PROJECT_NAMEServiceShipOrderResult() interface{} {
	return svc.NewGS_PROJECT_NAMEServiceShipOrderResult()
}

func newGS_PROJECT_NAMEServiceRegisterUserArgs() interface{} {
	return svc.NewGS_PROJECT_NAMEServiceRegisterUserArgs()
}
func newGS_PROJECT_NAMEServiceRegisterUserResult() interface{} {
	return svc.NewGS_PROJECT_NAMEServiceRegisterUserResult()
}

func newGS_PROJECT_NAMEServiceUpgradeUserArgs() interface{} {
	return svc.NewGS_PROJECT_NAMEServiceUpgradeUserArgs()
}
func newGS_PROJECT_NAMEServiceUpgradeUserResult() interface{} {
	return svc.NewGS_PROJECT_NAMEServiceUpgradeUserResult()
}

// NewServer is the entry point mirrored from kitex_gen: in a real build it
// takes a svc.GS_PROJECT_NAMEService handler plus server.Option values and
// returns a *server.Server bound to NewServiceInfo(). The template keeps the
// signature as a TODO so kitexsvr.Server.Run has an obvious call target.
//
// TODO: uncomment when the real kitex dep is in go.mod:
//
//	func NewServer(handler svc.GS_PROJECT_NAMEService, opts ...server.Option) server.Server {
//	    svr := server.NewServer(opts...)
//	    if err := svr.RegisterService(NewServiceInfo(), handler); err != nil {
//	        panic(err)
//	    }
//	    return svr
//	}
