spring.gorm.postgres.primary.host=127.0.0.1
spring.gorm.postgres.primary.port=5432
spring.gorm.postgres.primary.user=postgres
spring.gorm.postgres.primary.password=123456
spring.gorm.postgres.primary.db=test
spring.gorm.postgres.primary.sslmode=disable

spring.gorm.postgres.replica.host=127.0.0.1
spring.gorm.postgres.replica.port=5432
spring.gorm.postgres.replica.user=postgres
spring.gorm.postgres.replica.password=123456
spring.gorm.postgres.replica.db=test
spring.gorm.postgres.replica.sslmode=disable
