// Code generated by gs-http-gen compiler. DO NOT EDIT.

package proto

import (
	"fmt"
	"net/http"
	"strings"

	"go-spring.org/stdlib/errutil"
)

var _ = strings.Count
var _ = http.NewServeMux

// Error codes
type ErrCode int32

const (
	ErrCode_ErrOk       ErrCode = 0
	ErrCode_PARAM_ERROR ErrCode = 100003
)

var (
	ErrCode_name = map[ErrCode]string{
		0:      "ErrOk",
		100003: "PARAM_ERROR",
	}
	ErrCode_value = map[string]ErrCode{
		"ErrOk":       0,
		"PARAM_ERROR": 100003,
	}
)

// ErrCodeAsString wraps ErrCode to encode/decode as a JSON string
type ErrCodeAsString ErrCode

// MarshalJSON implements custom JSON encoding for the enum as a string
func (x ErrCodeAsString) MarshalJSON() ([]byte, error) {
	if s, ok := ErrCode_name[ErrCode(x)]; ok {
		return fmt.Appendf(nil, "\"%s\"", s), nil
	}
	return nil, errutil.Explain(nil, "invalid ErrCode: %d", x)
}

// UnmarshalJSON implements custom JSON decoding for the enum from a string
func (x *ErrCodeAsString) UnmarshalJSON(data []byte) error {
	str := strings.Trim(string(data), "\"")
	if v, ok := ErrCode_value[str]; ok {
		*x = ErrCodeAsString(v)
		return nil
	}
	return errutil.Explain(nil, "invalid ErrCode value: %q", str)
}

// OneOfErrCode is usually used for validation.
func OneOfErrCode(i ErrCode) bool {
	_, ok := ErrCode_name[i]
	return ok
}
