/*
 * Copyright 2025 The Go-Spring Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Package handler holds the WebSocket entry point. Unlike the sibling
// greet-api, there is no routes.go generated by goctl: go-zero's .api DSL
// only understands request/response HTTP endpoints, so there is no way to
// declare a WS route in an .api file, and no goctl stage produces a
// routes.go for us. The route table is therefore hand-written and attached
// directly by the HandlerRegister bean in provider/handler.go.
package handler

import (
	"encoding/json"
	"net/http"

	"github.com/gorilla/websocket"
	"github.com/zeromicro/go-zero/core/logx"

	"greetws/internal/svc"
	"greetws/internal/types"
)

// upgrader turns an inbound HTTP request into a WebSocket connection. The
// zero-value CheckOrigin rejects cross-origin browser clients by default;
// this example allows all origins because the consumer is a local process,
// not a browser, and adding an allow-list would only obscure the flow.
var upgrader = websocket.Upgrader{
	ReadBufferSize:  1024,
	WriteBufferSize: 1024,
	CheckOrigin:     func(r *http.Request) bool { return true },
}

// GreetWSHandler returns an http.HandlerFunc that upgrades the request to a
// WebSocket connection and, for each JSON frame it receives, invokes the
// injected GreetLogic bean and writes the response frame back.
//
// This is the piece that differs from the sibling greet-api handler:
//   - The handler owns the connection for its whole lifetime instead of
//     returning after a single request/response.
//   - httpx.Parse / httpx.OkJsonCtx are irrelevant once the connection is
//     upgraded; framing goes through websocket.Conn.
//   - The upgrade only works if the underlying http.ResponseWriter supports
//     http.Hijacker. go-zero's rest.Server response wrapper does support
//     hijacking, so we can add a WS route the same way we would any REST
//     route (see provider/handler.go).
func GreetWSHandler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		conn, err := upgrader.Upgrade(w, r, nil)
		if err != nil {
			// Upgrade already wrote the HTTP error response; just log.
			logx.WithContext(r.Context()).Errorf("ws upgrade failed: %v", err)
			return
		}
		defer conn.Close()

		ctx := r.Context()
		for {
			mt, data, err := conn.ReadMessage()
			if err != nil {
				// A normal client-side Close arrives as CloseNormalClosure
				// or a *net.OpError; either way there is nothing to log.
				if websocket.IsUnexpectedCloseError(err,
					websocket.CloseNormalClosure,
					websocket.CloseGoingAway) {
					logx.WithContext(ctx).Errorf("ws read: %v", err)
				}
				return
			}
			if mt != websocket.TextMessage && mt != websocket.BinaryMessage {
				continue
			}

			var req types.GreetReq
			if err := json.Unmarshal(data, &req); err != nil {
				_ = conn.WriteMessage(websocket.TextMessage,
					[]byte(`{"error":"bad json"}`))
				continue
			}

			resp, err := svcCtx.Logic.Greet(ctx, &req)
			if err != nil {
				_ = conn.WriteMessage(websocket.TextMessage,
					[]byte(`{"error":"logic failed"}`))
				continue
			}

			out, err := json.Marshal(resp)
			if err != nil {
				return
			}
			if err := conn.WriteMessage(websocket.TextMessage, out); err != nil {
				logx.WithContext(ctx).Errorf("ws write: %v", err)
				return
			}
		}
	}
}

