apiVersion: v1
kind: Service
metadata:
  name: GS_APP_NAME
  labels:
    app.kubernetes.io/name: GS_APP_NAME
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: GS_APP_NAME
  ports:
    - name: http
      port: GS_APP_PORT
      targetPort: http
    - name: management
      port: GS_MGMT_PORT
      targetPort: management
