spring.gorm.user=root
spring.gorm.password=123456
spring.gorm.addr=127.0.0.1:3306
spring.gorm.db=test

spring.gorm.instances.a.user=root
spring.gorm.instances.a.password=123456
spring.gorm.instances.a.addr=127.0.0.1:3306
spring.gorm.instances.a.db=test

spring.gorm.instances.b.user=root
spring.gorm.instances.b.password=123456
spring.gorm.instances.b.addr=127.0.0.1:3306
spring.gorm.instances.b.db=test