/*
 * Copyright 2025 The Go-Spring Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Package StarterHTTPClient wires declarative HTTP clients into the Go-Spring
// container. It is the runtime half of the OpenFeign / @HttpExchange equivalent:
// the call sites are generated by gs-http-gen (they hold only a Target), and
// this starter assembles the process-wide transport those calls dispatch
// through (by replacing httpclt.DoRequest) with service discovery, load
// balancing, resilience and trace propagation already in place — so a
// microservice call no longer means hand-wiring a discovery resolver and a
// circuit breaker per client.
package StarterHTTPClient

import (
	"context"
	"io"
	"net/http"
	"sort"
	"sync"

	"go-spring.org/cloud/discovery"
	"go-spring.org/log"
	"go-spring.org/spring/gs"
	"go-spring.org/stdlib/errutil"
	"go-spring.org/stdlib/flatten"
	"go-spring.org/stdlib/httpclt"
)

func init() {
	// Two beans, one module:
	//   1. dispatchTransport — the process-wide transport. The config is
	//      multi-entry (spring.http-client.*), but the transport is single:
	//      every entry contributes one route keyed by its target (addr or
	//      service-name), so a generated client only carries a Target.
	//   2. doRequestHook — replaces httpclt.DoRequest (the single send seam of
	//      stdlib/httpclt) with one that routes through the transport; exported
	//      as a Rooter so the pair is instantiated even when nothing autowires
	//      it. OnProperty gates both off when nothing is configured.
	gs.Module(gs.OnProperty("spring.http-client"), func(r gs.BeanProvider, _ flatten.Storage) error {

		r.Provide(newDispatchTransport,
			gs.IndexArg(1, gs.TagArg("${spring.http-client}")),
			gs.IndexArg(2, gs.TagArg("?")),
			gs.IndexArg(3, gs.TagArg("?")),
		).Destroy((*dispatchTransport).Close).Caller(1)

		r.Provide(newDoRequestHook,
			gs.IndexArg(0, gs.TagArg("")),
		).Export(gs.As[gs.Rooter]()).Caller(1)
		return nil
	})
}

// newDispatchTransport assembles the process-wide dispatch transport (one route
// per configured entry). Each entry's transport carries the trace layer,
// discovery + load balancing, resilience and the driver wrap. backends is every
// named discovery backend bean in the container (bean name = label); each entry
// resolves its ${discovery} label against it, so different entries may cite
// different registries.
func newDispatchTransport(ctx *gs.ContextProvider, cfgs map[string]Config, d Driver, backends map[string]discovery.Discovery) (*dispatchTransport, error) {
	dt := &dispatchTransport{routes: make(map[string]http.RoundTripper)}
	for name, c := range cfgs {
		if c.Discovery != "" {
			b, ok := backends[c.Discovery]
			if !ok {
				labels := make([]string, 0, len(backends))
				for k := range backends {
					labels = append(labels, k)
				}
				sort.Strings(labels)
				return nil, errutil.Explain(nil, "http-client: entry %q cites discovery backend %q but no such bean exists (registered: %v)", name, c.Discovery, labels)
			}
			c.backend = b
		}
		rt, closeFn, err := assembleTransport(ctx, name, c, d)
		if err != nil {
			return nil, err
		}
		dt.routes[routeKey(c)] = rt
		if closeFn != nil {
			dt.closers = append(dt.closers, closeFn)
		}
	}
	return dt, nil
}

// assembleTransport assembles one entry's RoundTripper through the process-wide
// Driver bean (the bundled DefaultDriver when none is provided). closeFn (when
// non-nil) releases the discovery watch and resilience executor behind it.
func assembleTransport(ctx *gs.ContextProvider, name string, c Config, d Driver) (rt http.RoundTripper, closeFn func() error, err error) {
	if err = c.validate(); err != nil {
		return nil, nil, err
	}
	// No company Driver bean → fall back to the bundled default assembly. Resolved
	// here (per entry) so this is the single place a nil driver is handled.
	if d == nil {
		d = DefaultDriver{}
	}
	// assembleTransport is also exercised directly by tests with a nil provider;
	// fall back to a bare context so the driver sees a non-nil one regardless.
	gctx := context.Background()
	if ctx != nil {
		gctx = ctx.Context
	}
	log.Debugf(gctx, log.TagAppDef, "assembling http transport, addr=%s service-name=%s", c.Addr, c.ServiceName)
	rt, closeFn, err = d.CreateTransport(gctx, name, c)
	if err != nil {
		log.Errorf(gctx, log.TagAppDef, "http-client: create transport failed: %v", err)
		return nil, nil, err
	}
	return rt, closeFn, nil
}

// routeKey returns the dispatch key for an entry: its direct address, or its
// service name when routing through discovery. This is the Target a generated
// client sets, and the value dispatchTransport matches against req.Host.
func routeKey(c Config) string {
	if c.Addr != "" {
		return c.Addr
	}
	return c.ServiceName
}

// dispatchTransport routes each request by req.Host to the transport assembled
// for that target. It is the single process-wide transport installed by
// replacing httpclt.DoRequest; Close releases every route's resources.
type dispatchTransport struct {
	mu      sync.RWMutex
	routes  map[string]http.RoundTripper
	closers []func() error
}

func (d *dispatchTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	d.mu.RLock()
	rt := d.routes[req.Host]
	d.mu.RUnlock()
	if rt == nil {
		return nil, errutil.Explain(nil, "http-client: no transport for target %q", req.Host)
	}
	return rt.RoundTrip(req)
}

func (d *dispatchTransport) Close() error {
	for _, closeFn := range d.closers {
		if err := closeFn(); err != nil {
			return err
		}
	}
	return nil
}

// doRequestHook is the marker bean owning the httpclt.DoRequest replacement:
// while it is live, every generated client and imperative helper routes through
// the dispatch transport.
type doRequestHook struct{}

// newDoRequestHook replaces httpclt.DoRequest with one routing through the
// dispatch transport. The client is deliberately constructed without a
// Timeout: per-target timeouts belong to the resilience policy of each entry,
// not to a single process-wide hard timeout that would apply to every route.
func newDoRequestHook(d *dispatchTransport) (*doRequestHook, error) {
	client := &http.Client{Transport: d}
	httpclt.DoRequest = func(req *http.Request, meta httpclt.Metadata, fn func(io.Reader) error) (*http.Response, error) {
		resp, err := client.Do(req)
		if err != nil {
			return nil, err
		}
		defer func() { _ = resp.Body.Close() }()
		if err = fn(resp.Body); err != nil {
			return nil, err
		}
		return resp, nil
	}
	log.Infof(context.Background(), log.TagAppDef, "http client initialized, routes=%d", len(d.routes))
	return &doRequestHook{}, nil
}
