/*
 * Copyright 2025 The Go-Spring Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Package StarterHTTPClient wires declarative HTTP clients into the Go-Spring
// container. It is the runtime half of the OpenFeign / @HttpExchange equivalent:
// the call sites are generated by gs-http-gen (they hold only a Target), and
// this starter assembles one transport per configured target and installs it by
// replacing httpclt.DoRequest, with service discovery, load balancing, resilience
// and trace propagation already in place — so a microservice call no longer means
// hand-wiring a discovery resolver and a circuit breaker per client.
package StarterHTTPClient

import (
	"context"
	"io"
	"net/http"
	"sort"

	"go-spring.org/cloud/discovery"
	"go-spring.org/log"
	"go-spring.org/spring/conf"
	"go-spring.org/spring/gs"
	"go-spring.org/stdlib/errutil"
	"go-spring.org/stdlib/flatten"
	"go-spring.org/stdlib/httpclt"
)

func init() {
	// Three beans, one module:
	//   1. route — one per entry under ${spring.http-client.instances}. Each
	//      entry's transport carries the trace layer, discovery + load balancing,
	//      resilience and the driver wrap, and holds its own target (addr or
	//      service-name), so a generated client only carries a Target.
	//   2. dispatchTransport — the process-wide route table collecting them.
	//   3. doRequestHook — replaces httpclt.DoRequest (the single send seam of
	//      stdlib/httpclt) with one that looks the route up by the call's Target;
	//      exported as a Rooter so the trio is instantiated even when nothing
	//      autowires it.
	//
	// Gated on the instances bucket, not on the family prefix: ${spring.http-client
	// .default} holds family-wide values and configures no client on its own, so a
	// process that sets only defaults must not take over httpclt.DoRequest with an
	// empty route table.
	gs.Module(gs.OnProperty("spring.http-client.instances"), func(r gs.BeanProvider, p flatten.Storage) error {

		// Entries are provided one bean at a time so each selects its own Driver.
		// The Driver param (index 3) is selected by the entry's
		// ${spring.http-client.instances.<name>.driver}, falling back to the
		// family-wide ${spring.http-client.default.driver}, then to "?"
		// (nullable by-type — injects the single Driver bean when a company
		// provides one, nil otherwise, and assembleTransport falls back to
		// DefaultDriver). Naming a bean that does not exist fails loud.
		if err := conf.BindEach(p, "${spring.http-client.instances}", func(name string, c Config) error {
			r.Provide(newRoute,
				gs.IndexArg(1, gs.ValueArg(name)),
				gs.IndexArg(2, gs.ValueArg(c)),
				gs.IndexArg(3, gs.TagArg("${spring.http-client.instances."+name+".driver:=${spring.http-client.default.driver:=?}}")),
				gs.IndexArg(4, gs.TagArg("?")),
			).Name(name).Destroy((*route).Close).Caller(1)
			return nil
		}); err != nil {
			return err
		}

		r.Provide(newDispatchTransport,
			gs.IndexArg(0, gs.TagArg("?")),
		).Caller(1)

		r.Provide(newDoRequestHook,
			gs.IndexArg(0, gs.TagArg("")),
		).Export(gs.As[gs.Rooter]()).Caller(1)
		return nil
	})
}

// newRoute assembles one entry's transport. backends is every named discovery
// backend bean in the container (bean name = label); the entry resolves its
// ${discovery} label against it, so different entries may cite different
// registries.
func newRoute(ctx *gs.ContextProvider, name string, c Config, d Driver, backends map[string]discovery.Discovery) (*route, error) {
	var backend discovery.Discovery
	if c.Discovery != "" {
		b, ok := backends[c.Discovery]
		if !ok {
			labels := make([]string, 0, len(backends))
			for k := range backends {
				labels = append(labels, k)
			}
			sort.Strings(labels)
			return nil, errutil.Explain(nil, "http-client: entry %q cites discovery backend %q but no such bean exists (registered: %v)", name, c.Discovery, labels)
		}
		backend = b
	}
	rt, closeFn, err := assembleTransport(ctx, name, c, backend, d)
	if err != nil {
		return nil, err
	}
	return &route{target: routeKey(c), rt: rt, closeFn: closeFn}, nil
}

// Close releases the discovery watch and resilience executor behind this route.
func (r *route) Close() error {
	if r.closeFn == nil {
		return nil
	}
	return r.closeFn()
}

// newDispatchTransport collects every route bean into the route table the
// DoRequest hook looks targets up in.
func newDispatchTransport(routes []*route) (*dispatchTransport, error) {
	dt := &dispatchTransport{routes: make(map[string]http.RoundTripper, len(routes))}
	for _, r := range routes {
		// Two entries addressing the same target would make the routing
		// nondeterministic; entries are collected in bean-name order, so this
		// reports the same pair every run.
		if _, dup := dt.routes[r.target]; dup {
			return nil, errutil.Explain(nil, "http-client: two entries resolve to the same target %q; targets must be unique", r.target)
		}
		dt.routes[r.target] = r.rt
	}
	return dt, nil
}

// assembleTransport assembles one entry's RoundTripper through the process-wide
// Driver bean (the bundled DefaultDriver when none is provided). backend is the
// entry's already-resolved discovery backend (nil when it cites none). closeFn
// (when non-nil) releases the discovery watch and resilience executor behind it.
func assembleTransport(ctx *gs.ContextProvider, name string, c Config, backend discovery.Discovery, d Driver) (rt http.RoundTripper, closeFn func() error, err error) {
	if err = c.validate(); err != nil {
		return nil, nil, err
	}
	// No company Driver bean → fall back to the bundled default assembly. Resolved
	// here (per entry) so this is the single place a nil driver is handled.
	if d == nil {
		d = DefaultDriver{}
	}
	// assembleTransport is also exercised directly by tests with a nil provider;
	// fall back to a bare context so the driver sees a non-nil one regardless.
	gctx := context.Background()
	if ctx != nil {
		gctx = ctx.Context
	}
	log.Debugf(gctx, log.TagAppDef, "assembling http transport, addr=%s service-name=%s", c.Addr, c.ServiceName)
	rt, closeFn, err = d.CreateTransport(gctx, name, c, backend)
	if err != nil {
		log.Errorf(gctx, log.TagAppDef, "http-client: create transport failed: %v", err)
		return nil, nil, err
	}
	return rt, closeFn, nil
}

// routeKey returns the dispatch key for an entry: its direct address, or its
// service name when routing through discovery. This is the Target a call
// declares, and the value dispatchTransport matches against.
func routeKey(c Config) string {
	if c.Addr != "" {
		return c.Addr
	}
	return c.ServiceName
}

// route is one configured entry: the target calls address it by, and the
// transport assembled for it.
type route struct {
	// target is the entry's route key — its addr, or its service name when
	// routing through discovery. It is what a call declares as its Target.
	target string

	rt      http.RoundTripper
	closeFn func() error
}

// dispatchTransport is the process-wide route table: one assembled transport per
// configured target. Routing happens at the DoRequest hook, where the call's
// declared Metadata.Target is still in hand — deliberately not inside a
// RoundTripper method, which net/http calls with nothing but an *http.Request
// and would force the target to be smuggled back through a URL field.
type dispatchTransport struct {
	// routes is sealed once newDispatchTransport returns; read-only afterwards,
	// so concurrent lookups need no lock.
	routes map[string]http.RoundTripper
}

// transport returns the transport assembled for the target a call declares, or
// an error naming the target when no entry registered it.
func (d *dispatchTransport) transport(target string) (http.RoundTripper, error) {
	if target == "" {
		return nil, errutil.Explain(nil, "http-client: the call declares no target; httpclt.Metadata.Target selects the configured entry")
	}
	rt, ok := d.routes[target]
	if !ok {
		return nil, errutil.Explain(nil, "http-client: no transport for target %q", target)
	}
	return rt, nil
}

// doRequestHook is the marker bean owning the httpclt.DoRequest replacement:
// while it is live, every generated client and imperative helper is dispatched
// to the transport of the target it declares.
type doRequestHook struct{}

// newDoRequestHook replaces httpclt.DoRequest with one that picks the entry's
// transport from the call's declared Metadata.Target and drives the call through
// it. The client is deliberately constructed without a Timeout: per-target
// timeouts belong to the resilience policy of each entry, not to a single
// process-wide hard timeout that would apply to every route.
func newDoRequestHook(d *dispatchTransport) (*doRequestHook, error) {
	// A failed newDispatchTransport is reported and then yields a nil here rather
	// than aborting wiring, so fail this bean the same way instead of panicking.
	if d == nil {
		return nil, errutil.Explain(nil, "http-client: the route table failed to assemble; see the earlier construct error")
	}
	httpclt.DoRequest = func(req *http.Request, meta httpclt.Metadata, fn func(io.Reader) error) (*http.Response, error) {
		rt, err := d.transport(meta.Target)
		if err != nil {
			return nil, err
		}
		// A fresh client per call is deliberate: it is a small value, the
		// connection pool lives in the route's own transport, and it keeps every
		// hop of a redirect on the same route.
		resp, err := (&http.Client{Transport: rt}).Do(req)
		if err != nil {
			return nil, err
		}
		defer func() { _ = resp.Body.Close() }()
		if err = fn(resp.Body); err != nil {
			return nil, err
		}
		return resp, nil
	}
	log.Infof(context.Background(), log.TagAppDef, "http client initialized, routes=%d", len(d.routes))
	return &doRequestHook{}, nil
}
