/*
 * Copyright 2025 The Go-Spring Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Package StarterHTTPClient wires declarative HTTP clients into the Go-Spring
// container. It is the runtime half of the OpenFeign / @HttpExchange equivalent:
// the call sites are generated by gs-http-gen (they only hold an *http.Client),
// and this starter provides that client with service discovery, load balancing,
// resilience and trace propagation already assembled — so a microservice call
// no longer means hand-wiring a LiveDialer and a circuit breaker per client.
package StarterHTTPClient

import (
	"io"
	"net/http"

	"go-spring.org/spring/gs"
	"go-spring.org/spring/httpx"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
)

func init() {
	// Multi-instance only: bind a map of clients under "${spring.http-client}"
	// and register one named *http.Client per entry, matching the client-starter
	// archetype (no default singleton). An application injects an instance by
	// name (autowire:"user-svc") and sets it on a generated client's HTTPClient
	// field. Each instance owns a discovery watch and/or resilience executor, so
	// a destroy hook releases them.
	gs.Group("${spring.http-client}", newClient, destroyClient)
}

// newClient assembles one declarative-HTTP-client instance. The base transport
// is otelhttp-instrumented so every outbound request emits a client span through
// the OTel globals starter-otel installs (a no-op when it is absent), which is
// how trace context rides across service boundaries. stdlib/httpx then layers
// discovery + load balancing and, when enabled, resilience on top of that base.
func newClient(c Config) (*http.Client, error) {
	if err := c.validate(); err != nil {
		return nil, err
	}
	base := otelhttp.NewTransport(http.DefaultTransport)
	rt, closeFn, err := httpx.NewTransport(c.toTransportConfig(base))
	if err != nil {
		return nil, err
	}
	return &http.Client{
		Transport: &managedTransport{rt: rt, closeFn: closeFn},
		Timeout:   c.Timeout,
	}, nil
}

// destroyClient releases the discovery watch and resilience executor behind an
// instance by closing its transport.
func destroyClient(client *http.Client) error {
	if c, ok := client.Transport.(io.Closer); ok {
		return c.Close()
	}
	return nil
}

// managedTransport ties the assembled transport to its cleanup so a per-instance
// destroy hook can stop the discovery watch and close the resilience executor
// through the standard io.Closer type-assertion.
type managedTransport struct {
	rt      http.RoundTripper
	closeFn func() error
}

func (m *managedTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	return m.rt.RoundTrip(req)
}

func (m *managedTransport) Close() error { return m.closeFn() }
