# Define a go-redis client instance
spring.go-redis.main.addr=127.0.0.1:6379

# Define a redigo client instance
spring.redigo.main.addr=127.0.0.1:6379

# Define a MySQL instance with GORM
spring.gorm.main.url=root:123456@(127.0.0.1:3306)/test?timeout=500ms&readTimeout=500ms&writeTimeout=500ms&charset=utf8&parseTime=true&loc=Local
