spring.xxljob.instances.a.app-name=go-spring-demo
spring.xxljob.instances.a.admin-addresses=http://127.0.0.1:18081
spring.xxljob.instances.a.port=9999
spring.xxljob.instances.a.registry-interval=5s
spring.xxljob.instances.a.log-dir=./logs
