// Code generated by gs-mock v0.0.8. DO NOT EDIT.
// Tool: https://github.com/go-spring/gs-mock
// gs mock -o src_mock.go -i '!RepositoryV2,,GenericService,Service,,Repository'

package example

import (
	"context"
	exp "github.com/go-spring/gs-mock/example/inner"
	"github.com/go-spring/gs-mock/gsmock"
	"io"
	"net/http"
)

// RepositoryMockImpl is a generated mock implementation of the Repository interface.
type RepositoryMockImpl[T ~int | ~uint, Req *http.Request] struct {
	r *gsmock.Manager
}

// NewRepositoryMockImpl creates a new mock instance for Repository with the given
// gsmock.Manager. Returns an initialized struct ready for registering mock behavior.
func NewRepositoryMockImpl[T ~int | ~uint, Req *http.Request](r *gsmock.Manager) *RepositoryMockImpl[T, Req] {
	return &RepositoryMockImpl[T, Req]{r: r}
}

//go:noinline
func (impl *RepositoryMockImpl[T, Req]) funcFindByID() func(id string) (T, error) {
	return impl.FindByID
}

// FindByID calls the registered mock for FindByID via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *RepositoryMockImpl[T, Req]) FindByID(id string) (T, error) {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcFindByID(), id); ok {
		return gsmock.Unbox2[T, error](ret)
	}
	panic("no mock code matched for RepositoryMockImpl.FindByID")
}

// MockFindByID returns a Mocker12
// for registering mock behavior of FindByID with specific parameter and return types.
func (impl *RepositoryMockImpl[T, Req]) MockFindByID() *gsmock.Mocker12[string, T, error] {
	return gsmock.Method12(impl, impl.funcFindByID(), impl.r)
}

//go:noinline
func (impl *RepositoryMockImpl[T, Req]) funcSave() func(item T) error {
	return impl.Save
}

// Save calls the registered mock for Save via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *RepositoryMockImpl[T, Req]) Save(item T) error {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcSave(), item); ok {
		return gsmock.Unbox1[error](ret)
	}
	panic("no mock code matched for RepositoryMockImpl.Save")
}

// MockSave returns a Mocker11
// for registering mock behavior of Save with specific parameter and return types.
func (impl *RepositoryMockImpl[T, Req]) MockSave() *gsmock.Mocker11[T, error] {
	return gsmock.Method11(impl, impl.funcSave(), impl.r)
}

// GenericServiceMockImpl is a generated mock implementation of the GenericService interface.
type GenericServiceMockImpl[R any, S any] struct {
	io.Writer

	r *gsmock.Manager
}

// NewGenericServiceMockImpl creates a new mock instance for GenericService with the given
// gsmock.Manager. Returns an initialized struct ready for registering mock behavior.
func NewGenericServiceMockImpl[R any, S any](r *gsmock.Manager) *GenericServiceMockImpl[R, S] {
	return &GenericServiceMockImpl[R, S]{r: r}
}

//go:noinline
func (impl *GenericServiceMockImpl[R, S]) funcInit() func() {
	return impl.Init
}

// Init calls the registered mock for Init via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *GenericServiceMockImpl[R, S]) Init() {
	if _, ok := gsmock.Invoke(impl.r, impl, impl.funcInit()); ok {
		return
	}
	panic("no mock code matched for GenericServiceMockImpl.Init")
}

// MockInit returns a Mocker00
// for registering mock behavior of Init with specific parameter and return types.
func (impl *GenericServiceMockImpl[R, S]) MockInit() *gsmock.Mocker00 {
	return gsmock.Method00(impl, impl.funcInit(), impl.r)
}

//go:noinline
func (impl *GenericServiceMockImpl[R, S]) funcDefault() func() S {
	return impl.Default
}

// Default calls the registered mock for Default via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *GenericServiceMockImpl[R, S]) Default() S {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcDefault()); ok {
		return gsmock.Unbox1[S](ret)
	}
	panic("no mock code matched for GenericServiceMockImpl.Default")
}

// MockDefault returns a Mocker01
// for registering mock behavior of Default with specific parameter and return types.
func (impl *GenericServiceMockImpl[R, S]) MockDefault() *gsmock.Mocker01[S] {
	return gsmock.Method01(impl, impl.funcDefault(), impl.r)
}

//go:noinline
func (impl *GenericServiceMockImpl[R, S]) funcTryDefault() func() (S, bool) {
	return impl.TryDefault
}

// TryDefault calls the registered mock for TryDefault via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *GenericServiceMockImpl[R, S]) TryDefault() (S, bool) {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcTryDefault()); ok {
		return gsmock.Unbox2[S, bool](ret)
	}
	panic("no mock code matched for GenericServiceMockImpl.TryDefault")
}

// MockTryDefault returns a Mocker02
// for registering mock behavior of TryDefault with specific parameter and return types.
func (impl *GenericServiceMockImpl[R, S]) MockTryDefault() *gsmock.Mocker02[S, bool] {
	return gsmock.Method02(impl, impl.funcTryDefault(), impl.r)
}

//go:noinline
func (impl *GenericServiceMockImpl[R, S]) funcAccept() func(r0 R) {
	return impl.Accept
}

// Accept calls the registered mock for Accept via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *GenericServiceMockImpl[R, S]) Accept(r0 R) {
	if _, ok := gsmock.Invoke(impl.r, impl, impl.funcAccept(), r0); ok {
		return
	}
	panic("no mock code matched for GenericServiceMockImpl.Accept")
}

// MockAccept returns a Mocker10
// for registering mock behavior of Accept with specific parameter and return types.
func (impl *GenericServiceMockImpl[R, S]) MockAccept() *gsmock.Mocker10[R] {
	return gsmock.Method10(impl, impl.funcAccept(), impl.r)
}

//go:noinline
func (impl *GenericServiceMockImpl[R, S]) funcConvert() func(r0 R) S {
	return impl.Convert
}

// Convert calls the registered mock for Convert via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *GenericServiceMockImpl[R, S]) Convert(r0 R) S {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcConvert(), r0); ok {
		return gsmock.Unbox1[S](ret)
	}
	panic("no mock code matched for GenericServiceMockImpl.Convert")
}

// MockConvert returns a Mocker11
// for registering mock behavior of Convert with specific parameter and return types.
func (impl *GenericServiceMockImpl[R, S]) MockConvert() *gsmock.Mocker11[R, S] {
	return gsmock.Method11(impl, impl.funcConvert(), impl.r)
}

//go:noinline
func (impl *GenericServiceMockImpl[R, S]) funcTryConvert() func(r0 R) (S, bool) {
	return impl.TryConvert
}

// TryConvert calls the registered mock for TryConvert via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *GenericServiceMockImpl[R, S]) TryConvert(r0 R) (S, bool) {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcTryConvert(), r0); ok {
		return gsmock.Unbox2[S, bool](ret)
	}
	panic("no mock code matched for GenericServiceMockImpl.TryConvert")
}

// MockTryConvert returns a Mocker12
// for registering mock behavior of TryConvert with specific parameter and return types.
func (impl *GenericServiceMockImpl[R, S]) MockTryConvert() *gsmock.Mocker12[R, S, bool] {
	return gsmock.Method12(impl, impl.funcTryConvert(), impl.r)
}

//go:noinline
func (impl *GenericServiceMockImpl[R, S]) funcProcess() func(r0 context.Context, r1 map[string]R) (S, error) {
	return impl.Process
}

// Process calls the registered mock for Process via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *GenericServiceMockImpl[R, S]) Process(r0 context.Context, r1 map[string]R) (S, error) {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcProcess(), r0, r1); ok {
		return gsmock.Unbox2[S, error](ret)
	}
	panic("no mock code matched for GenericServiceMockImpl.Process")
}

// MockProcess returns a Mocker22
// for registering mock behavior of Process with specific parameter and return types.
func (impl *GenericServiceMockImpl[R, S]) MockProcess() *gsmock.Mocker22[context.Context, map[string]R, S, error] {
	return gsmock.Method22(impl, impl.funcProcess(), impl.r)
}

//go:noinline
func (impl *GenericServiceMockImpl[R, S]) funcPrintf() func(format string, args ...any) {
	return impl.Printf
}

// Printf calls the registered mock for Printf via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *GenericServiceMockImpl[R, S]) Printf(format string, args ...any) {
	if _, ok := gsmock.Invoke(impl.r, impl, impl.funcPrintf(), format, args); ok {
		return
	}
	panic("no mock code matched for GenericServiceMockImpl.Printf")
}

// MockPrintf returns a VarMocker20
// for registering mock behavior of Printf with specific parameter and return types.
func (impl *GenericServiceMockImpl[R, S]) MockPrintf() *gsmock.VarMocker20[string, any] {
	return gsmock.VarMethod20(impl, impl.funcPrintf(), impl.r)
}

// ServiceMockImpl is a generated mock implementation of the Service interface.
type ServiceMockImpl struct {
	io.Writer

	r *gsmock.Manager
}

// NewServiceMockImpl creates a new mock instance for Service with the given
// gsmock.Manager. Returns an initialized struct ready for registering mock behavior.
func NewServiceMockImpl(r *gsmock.Manager) *ServiceMockImpl {
	return &ServiceMockImpl{r: r}
}

//go:noinline
func (impl *ServiceMockImpl) funcInit() func() {
	return impl.Init
}

// Init calls the registered mock for Init via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *ServiceMockImpl) Init() {
	if _, ok := gsmock.Invoke(impl.r, impl, impl.funcInit()); ok {
		return
	}
	panic("no mock code matched for ServiceMockImpl.Init")
}

// MockInit returns a Mocker00
// for registering mock behavior of Init with specific parameter and return types.
func (impl *ServiceMockImpl) MockInit() *gsmock.Mocker00 {
	return gsmock.Method00(impl, impl.funcInit(), impl.r)
}

//go:noinline
func (impl *ServiceMockImpl) funcDefault() func() *Response {
	return impl.Default
}

// Default calls the registered mock for Default via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *ServiceMockImpl) Default() *Response {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcDefault()); ok {
		return gsmock.Unbox1[*Response](ret)
	}
	panic("no mock code matched for ServiceMockImpl.Default")
}

// MockDefault returns a Mocker01
// for registering mock behavior of Default with specific parameter and return types.
func (impl *ServiceMockImpl) MockDefault() *gsmock.Mocker01[*Response] {
	return gsmock.Method01(impl, impl.funcDefault(), impl.r)
}

//go:noinline
func (impl *ServiceMockImpl) funcTryDefault() func() (*Response, bool) {
	return impl.TryDefault
}

// TryDefault calls the registered mock for TryDefault via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *ServiceMockImpl) TryDefault() (*Response, bool) {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcTryDefault()); ok {
		return gsmock.Unbox2[*Response, bool](ret)
	}
	panic("no mock code matched for ServiceMockImpl.TryDefault")
}

// MockTryDefault returns a Mocker02
// for registering mock behavior of TryDefault with specific parameter and return types.
func (impl *ServiceMockImpl) MockTryDefault() *gsmock.Mocker02[*Response, bool] {
	return gsmock.Method02(impl, impl.funcTryDefault(), impl.r)
}

//go:noinline
func (impl *ServiceMockImpl) funcAccept() func(r0 *exp.Request) {
	return impl.Accept
}

// Accept calls the registered mock for Accept via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *ServiceMockImpl) Accept(r0 *exp.Request) {
	if _, ok := gsmock.Invoke(impl.r, impl, impl.funcAccept(), r0); ok {
		return
	}
	panic("no mock code matched for ServiceMockImpl.Accept")
}

// MockAccept returns a Mocker10
// for registering mock behavior of Accept with specific parameter and return types.
func (impl *ServiceMockImpl) MockAccept() *gsmock.Mocker10[*exp.Request] {
	return gsmock.Method10(impl, impl.funcAccept(), impl.r)
}

//go:noinline
func (impl *ServiceMockImpl) funcConvert() func(r0 *exp.Request) *Response {
	return impl.Convert
}

// Convert calls the registered mock for Convert via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *ServiceMockImpl) Convert(r0 *exp.Request) *Response {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcConvert(), r0); ok {
		return gsmock.Unbox1[*Response](ret)
	}
	panic("no mock code matched for ServiceMockImpl.Convert")
}

// MockConvert returns a Mocker11
// for registering mock behavior of Convert with specific parameter and return types.
func (impl *ServiceMockImpl) MockConvert() *gsmock.Mocker11[*exp.Request, *Response] {
	return gsmock.Method11(impl, impl.funcConvert(), impl.r)
}

//go:noinline
func (impl *ServiceMockImpl) funcTryConvert() func(r0 *exp.Request) (*Response, bool) {
	return impl.TryConvert
}

// TryConvert calls the registered mock for TryConvert via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *ServiceMockImpl) TryConvert(r0 *exp.Request) (*Response, bool) {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcTryConvert(), r0); ok {
		return gsmock.Unbox2[*Response, bool](ret)
	}
	panic("no mock code matched for ServiceMockImpl.TryConvert")
}

// MockTryConvert returns a Mocker12
// for registering mock behavior of TryConvert with specific parameter and return types.
func (impl *ServiceMockImpl) MockTryConvert() *gsmock.Mocker12[*exp.Request, *Response, bool] {
	return gsmock.Method12(impl, impl.funcTryConvert(), impl.r)
}

//go:noinline
func (impl *ServiceMockImpl) funcProcess() func(r0 context.Context, r1 map[string]*exp.Request) (*Response, error) {
	return impl.Process
}

// Process calls the registered mock for Process via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *ServiceMockImpl) Process(r0 context.Context, r1 map[string]*exp.Request) (*Response, error) {
	if ret, ok := gsmock.Invoke(impl.r, impl, impl.funcProcess(), r0, r1); ok {
		return gsmock.Unbox2[*Response, error](ret)
	}
	panic("no mock code matched for ServiceMockImpl.Process")
}

// MockProcess returns a Mocker22
// for registering mock behavior of Process with specific parameter and return types.
func (impl *ServiceMockImpl) MockProcess() *gsmock.Mocker22[context.Context, map[string]*exp.Request, *Response, error] {
	return gsmock.Method22(impl, impl.funcProcess(), impl.r)
}

//go:noinline
func (impl *ServiceMockImpl) funcPrintf() func(format string, args ...any) {
	return impl.Printf
}

// Printf calls the registered mock for Printf via gsmock.Invoke.
// If no matching mock is registered, it panics.
func (impl *ServiceMockImpl) Printf(format string, args ...any) {
	if _, ok := gsmock.Invoke(impl.r, impl, impl.funcPrintf(), format, args); ok {
		return
	}
	panic("no mock code matched for ServiceMockImpl.Printf")
}

// MockPrintf returns a VarMocker20
// for registering mock behavior of Printf with specific parameter and return types.
func (impl *ServiceMockImpl) MockPrintf() *gsmock.VarMocker20[string, any] {
	return gsmock.VarMethod20(impl, impl.funcPrintf(), impl.r)
}
