# HTTP server settings.
spring.http.server.addr=0.0.0.0:8080

# Dynamic configuration settings.
dync.refresh.time=0

# Root logger settings.
logging.logger.root.type=FileLogger
logging.logger.root.level=INFO
logging.logger.root.dir=./logs
logging.logger.root.file=app.log
logging.logger.root.layout.type=JSONLayout
logging.logger.root.layout.fileLineMaxLength=20
